"""
data.py - Base de datos del simulador MMJ World Cup
Optimizado para Streamlit con soporte de banderas por imágenes
"""

# ---------------------------------------------------------------------------
# LISTAS DE EQUIPOS POR CONFEDERACIÓN
# ---------------------------------------------------------------------------
UEFA_TEAMS = [
    "Switzerland", "Denmark", "Poland", "Austria", "Croatia",
    "Sweden", "Serbia", "Wales", "Scotland", "Belgium",
    "Ukraine", "Czech Republic", "Iceland", "Greece", "Turkey",
    "Norway", "Netherlands", "France", "Spain", "Portugal",
    "Italy", "England", "Germany", "Hungary", "Israel"
]

CONMEBOL_TEAMS = [
    "Brazil", "Argentina", "Colombia", "Chile", "Peru",
    "Uruguay", "Venezuela", "Bolivia", "Paraguay", "Ecuador",
]

CAF_TEAMS = [
    "South Africa", "Morocco", "Tunisia", "Ghana", "Senegal",
    "Egypt", "Ivory Coast", "Cameroon", "Nigeria", "Algeria",
]

CONCACAF_TEAMS = ["Mexico", "Panama", "Costa Rica", "USA", "Canada", "Jamaica"]
AFC_TEAMS = ["Korea", "Saudi Arabia", "Japan", "Australia", "Iran", "Qatar"]
PLAYOFF_TEAMS = ["New Zealand"]

ALL_TEAMS = UEFA_TEAMS + CONMEBOL_TEAMS + CAF_TEAMS + CONCACAF_TEAMS + AFC_TEAMS + PLAYOFF_TEAMS
COPA_AMERICA_GUESTS_POOL = CONCACAF_TEAMS + AFC_TEAMS + CAF_TEAMS + PLAYOFF_TEAMS

# ---------------------------------------------------------------------------
# JUGADORES (mantengo tu lista completa, solo muestro un extracto aquí)
# ---------------------------------------------------------------------------
PLAYERS = {
    "Ukraine": [
        {"name": "V. Tsygankov", "pos": "MF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "O. Zinchenko", "pos": "DF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "R. Malinovskyi", "pos": "MF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "T. Stepanenko", "pos": "MF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "Y. Rakitskyi", "pos": "DF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "M. Shaparenko", "pos": "MF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "A. Lunin", "pos": "GK", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "V. Buyalskyi", "pos": "MF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "M. Matviienko", "pos": "DF", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
        {"name": "M. Mudryk", "pos": "FW", "nat": "ua", "nat_name": "Ucrania", "sofifa": 0},
    ],
    "Czech Republic": [
        {"name": "P. Schick", "pos": "FW", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "T. Soucek", "pos": "MF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "A. Barak", "pos": "MF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "V. Coufal", "pos": "DF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "A. Hložek", "pos": "FW", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "T. Holes", "pos": "MF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "L. Krejčí", "pos": "DF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "J. Pavlenka", "pos": "GK", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "V. Černý", "pos": "FW", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
        {"name": "M. Jurásek", "pos": "DF", "nat": "cz", "nat_name": "Rep. Checa", "sofifa": 0},
    ],
    "Iceland": [
        {"name": "S. Ingason", "pos": "DF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "A. Guðmundsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "H. Magnússon", "pos": "DF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "J. Guðmundsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "R. Rúnarsson", "pos": "GK", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "A. Sigurðsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "J. Þorsteinsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "M. Anderson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "H. Haraldsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
        {"name": "K. Hlynsson", "pos": "MF", "nat": "is", "nat_name": "Islandia", "sofifa": 0},
    ],
    "Greece": [
        {"name": "O. Vlachodimos", "pos": "GK", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "K. Mavropanos", "pos": "DF", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "V. Pavlidis", "pos": "FW", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "K. Tsimikas", "pos": "DF", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "A. Bakasetas", "pos": "MF", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "P. Mantalos", "pos": "MF", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "T. Fountas", "pos": "FW", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "T. Douvikas", "pos": "FW", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "G. Giakoumakis", "pos": "FW", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
        {"name": "G. Koutsias", "pos": "FW", "nat": "gr", "nat_name": "Grecia", "sofifa": 0},
    ],
    "Turkey": [
        {"name": "H. Çalhanoğlu", "pos": "MF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "O. Kökçü", "pos": "MF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "E. Ünal", "pos": "FW", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "U. Çakır", "pos": "GK", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "S. Özcan", "pos": "MF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "C. Ünder", "pos": "MF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "K.Aktürkoğlu", "pos": "FW", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "A. Bardakçı", "pos": "DF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "M. Demiral", "pos": "DF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
        {"name": "A. Güler", "pos": "MF", "nat": "tr", "nat_name": "Turquía", "sofifa": 0},
    ],
    "Brazil": [
        {"name": "Neymar Jr", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 190871},
        {"name": "Vini Jr.", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 238794},
        {"name": "Casemiro", "pos": "MF", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Allison", "pos": "GK", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Thiago Silva", "pos": "DF", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Marquinhos", "pos": "DF", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Gabriel Jesús", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Gabriel Martinelli", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Rodrygo", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
        {"name": "Matheus Martins", "pos": "FW", "nat": "br", "nat_name": "Brasil", "sofifa": 0},
    ],
    "Ecuador": [
        {"name": "M. Caicedo", "pos": "MF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "A. Obando", "pos": "MF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "P. Estupiñán", "pos": "DF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "P. Hincapié", "pos": "DF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "A. Alvarado", "pos": "GK", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "J. Sornoza", "pos": "MF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "D. Díaz", "pos": "FW", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "C. Ramírez", "pos": "MF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "M. Ramírez", "pos": "FW", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
        {"name": "K. Páez", "pos": "MF", "nat": "ec", "nat_name": "Ecuador", "sofifa": 0},
    ],
    "Paraguay": [
        {"name": "M. Almirón", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "Kaku", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "A. Sanabria", "pos": "FW", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "O. Alderete", "pos": "DF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "G. Ávalos", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "D. González", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "A. Bareiro", "pos": "FW", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "A. Cubas", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "J. Espínola", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
        {"name": "J. Enciso", "pos": "MF", "nat": "py", "nat_name": "Paraguay", "sofifa": 0},
    ],
    "Mexico": [
        {"name": "G. Ochoa", "pos": "GK", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "H. Lozano", "pos": "FW", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "S. Giménez", "pos": "FW", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "R. Jiménez", "pos": "FW", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "E. Álvarez", "pos": "MF", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "E. Sánchez", "pos": "DF", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "H. Herrera", "pos": "MF", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "L. Chávez", "pos": "MF", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "C. Montes", "pos": "DF", "nat": "mx", "nat_name": "México", "sofifa": 0},
        {"name": "J. Quiñones", "pos": "FW", "nat": "mx", "nat_name": "México", "sofifa": 0},
    ],
    "Panama": [
        {"name": "A. Murillo", "pos": "DF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "A. Godoy", "pos": "MF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "A. Carrasquilla", "pos": "MF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "A. Andrade", "pos": "DF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "I. Díaz", "pos": "FW", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "J. Rodríguez", "pos": "MF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "C. Waterman", "pos": "FW", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "L. Mejía", "pos": "DF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "J. Fajardo", "pos": "FW", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
        {"name": "E. Zorrilla", "pos": "MF", "nat": "pa", "nat_name": "Panamá", "sofifa": 0},
    ],
    "Italy": [
        {"name": "G. Donnarumma", "pos": "GK", "nat": "it", "nat_name": "Italia", "sofifa": 230666},
        {"name": "L. Pellegrini", "pos": "MF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "F. Dimarco", "pos": "DF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "N. Barella", "pos": "MF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "G. Di Lorenzo", "pos": "DF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "F. Chiesa", "pos": "FW", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "A. Bastoni", "pos": "DF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "C. Immobile", "pos": "FW", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "Jorginho", "pos": "MF", "nat": "it", "nat_name": "Italia", "sofifa": 0},
        {"name": "S. Pafundi", "pos": "FW", "nat": "it", "nat_name": "Italia", "sofifa": 0},
    ],
    "Portugal": [
        {"name": "Cristiano Ronaldo", "pos": "FW", "nat": "pt", "nat_name": "Portugal", "sofifa": 20801},
        {"name": "Rafael Leão", "pos": "FW", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "Rui Patricio", "pos": "GK", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "Rúben Dias", "pos": "DF", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "Bernardo Silva", "pos": "MF", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "João Cancelo", "pos": "DF", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "Diogo Jota", "pos": "FW", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "João Félix", "pos": "FW", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "Nuno Mendes", "pos": "DF", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
        {"name": "João Neves", "pos": "MF", "nat": "pt", "nat_name": "Portugal", "sofifa": 0},
    ],
    "Spain": [
        {"name": "Morata", "pos": "FW", "nat": "es", "nat_name": "España", "sofifa": 188350},
        {"name": "Gavi", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 261646},
        {"name": "Pedri", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 239318},
        {"name": "Carvajal", "pos": "DF", "nat": "es", "nat_name": "España", "sofifa": 178603},
        {"name": "U. Simón", "pos": "GK", "nat": "es", "nat_name": "España", "sofifa": 230869},
        {"name": "Rodri", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 231866},
        {"name": "Thiago", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 200145},
        {"name": "A. Grimaldo", "pos": "DF", "nat": "es", "nat_name": "España", "sofifa": 211704},
        {"name": "Koke", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 176580},
        {"name": "Stefan Bajcetic", "pos": "MF", "nat": "es", "nat_name": "España", "sofifa": 261215},
    ],
    "Korea": [
        {"name": "H. Son", "pos": "FW", "nat": "kr", "nat_name": "Corea", "sofifa": 202126},
        {"name": "Hyeon Woo", "pos": "GK", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Kim Min jae", "pos": "DF", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Lee Kang In", "pos": "MF", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Hwang Hee Chan", "pos": "FW", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Lee Jae Sung", "pos": "MF", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Hong Hyeon Seok", "pos": "MF", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Joo Min Kyu", "pos": "FW", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Um Won Sang", "pos": "GK", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
        {"name": "Kim Young Gwon", "pos": "DF", "nat": "kr", "nat_name": "Corea", "sofifa": 0},
    ],
    "Saudi Arabia": [
        {"name": "A. Al Mayoof", "pos": "GK", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "S. Al Faraj", "pos": "MF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "S. Al Dawsari", "pos": "FW", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "A. Sharahili", "pos": "DF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "S. Abdulhamid", "pos": "DF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "H. Tombakti", "pos": "MF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "F. Al Birekan", "pos": "MF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "A. Al Bulayhi", "pos": "DF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "Y. Al Shahrani", "pos": "DF", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
        {"name": "A. Al Ayeri", "pos": "FW", "nat": "sa", "nat_name": "Arabia Saudí", "sofifa": 0},
    ],
    "South Africa": [
        {"name": "J. Barr", "pos": "DF", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Foster", "pos": "FW", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Mothiba", "pos": "FW", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Hlongwane", "pos": "FW", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Links", "pos": "MF", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Cafú Phete", "pos": "MF", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Kodisang", "pos": "FW", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Blom", "pos": "MF", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Ngezana", "pos": "DF", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
        {"name": "Mailula", "pos": "FW", "nat": "za", "nat_name": "Sudáfrica", "sofifa": 0},
    ],
    "Tunisia": [
        {"name": "Dahmen", "pos": "GK", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Skhiri", "pos": "MF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Laïdouni", "pos": "MF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Talbi", "pos": "FW", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Khazri", "pos": "FW", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Bguir", "pos": "MF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Layouni", "pos": "MF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Valery", "pos": "DF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Abdi", "pos": "DF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
        {"name": "Bronn", "pos": "DF", "nat": "tn", "nat_name": "Túnez", "sofifa": 0},
    ],
    "Ghana": [
        {"name": "T. Partey", "pos": "MF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Iñaki williams", "pos": "FW", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "L. Zigi", "pos": "GK", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Kudus", "pos": "MF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Aidoo", "pos": "DF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Lamptey", "pos": "DF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Abdul Samed", "pos": "MF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Djiku", "pos": "DF", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Paintsil", "pos": "FW", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
        {"name": "Semenyo", "pos": "FW", "nat": "gh", "nat_name": "Ghana", "sofifa": 0},
    ],
    "New Zealand": [
        {"name": "C. Wood", "pos": "FW", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "J. Bell", "pos": "DF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "L. Cacace", "pos": "DF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "M. Stamenić", "pos": "MF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "A. Paulsen", "pos": "GK", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "A. Rufer", "pos": "FW", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "T. Bindon", "pos": "MF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "M. Boxall", "pos": "DF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "K. Barbarouses", "pos": "FW", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
        {"name": "B. Old", "pos": "MF", "nat": "nz", "nat_name": "Nueva Zelanda", "sofifa": 0},
    ],
    "Switzerland": [
        {"name": "G. Kobel", "pos": "GK", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "G. Xhaka", "pos": "MF", "nat": "ch", "nat_name": "Suiza", "sofifa": 190871},
        {"name": "M. Akanji", "pos": "DF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "F. Schär", "pos": "DF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "R. Freuler", "pos": "MF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "D. Zakaria", "pos": "MF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "N. Elvedi", "pos": "DF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "R. Rodríguez", "pos": "DF", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "B. Embolo", "pos": "FW", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
        {"name": "N. Okafor", "pos": "FW", "nat": "ch", "nat_name": "Suiza", "sofifa": 0},
    ],
    "Denmark": [
        {"name": "K. Schmeichel", "pos": "GK", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "A. Christensen", "pos": "DF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "P. Højbjerg", "pos": "MF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "S. Kjær", "pos": "DF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "M. Hjulmand", "pos": "MF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "C. Eriksen", "pos": "MF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "M. O'Riley", "pos": "MF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "J. Andersen", "pos": "DF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "A. Bah", "pos": "DF", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
        {"name": "R. Højlund", "pos": "FW", "nat": "dk", "nat_name": "Dinamarca", "sofifa": 0},
    ],
    "Poland": [
        {"name": "W. Szczęsny", "pos": "GK", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "R. Lewandowski", "pos": "FW", "nat": "pl", "nat_name": "Polonia", "sofifa": 188545},
        {"name": "P. Zieliński", "pos": "MF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "A. Milik", "pos": "FW", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "M. Cash", "pos": "DF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "S. Szymański", "pos": "MF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "P. Frankowski", "pos": "DF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "J. Kiwior", "pos": "DF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "N. Zalewski", "pos": "MF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
        {"name": "J. Bednarek", "pos": "DF", "nat": "pl", "nat_name": "Polonia", "sofifa": 0},
    ],
    "Austria": [
        {"name": "C. Stankovic", "pos": "GK", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "D. Alaba", "pos": "DF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "K. Laimer", "pos": "MF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "M. Sabitzer", "pos": "MF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "X. Schlager", "pos": "MF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "Arnautovic", "pos": "FW", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "K. Danso", "pos": "DF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "C. Baumgartner", "pos": "MF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "G. Trauner", "pos": "DF", "nat": "at", "nat_name": "Austria", "sofifa": 0},
        {"name": "M. Gregoritsch", "pos": "FW", "nat": "at", "nat_name": "Austria", "sofifa": 0},
    ],
    "Croatia": [
        {"name": "D. Livaković", "pos": "GK", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "L. Modrić", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 177003},
        {"name": "M. Brozović", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "M. Kovačić", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "J. Gvardiol", "pos": "DF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "A. Kramarić", "pos": "FW", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "I. Rakitić", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "M. Pasalic", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "N. Vlasic", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
        {"name": "L. Majer", "pos": "MF", "nat": "hr", "nat_name": "Croacia", "sofifa": 0},
    ],
    "Uruguay": [
        {"name": "F. Muslera", "pos": "GK", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "L. Suárez", "pos": "FW", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "F. Valverde", "pos": "MF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "R. Araujo", "pos": "DF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "J. Giménez", "pos": "DF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "D. Núñez", "pos": "FW", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "R. Bentancur", "pos": "MF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "L. Torreira", "pos": "MF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "S. Coates", "pos": "DF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
        {"name": "M. Ugarte", "pos": "MF", "nat": "uy", "nat_name": "Uruguay", "sofifa": 0},
    ],
    "Argentina": [
        {"name": "E. Martínez", "pos": "GK", "nat": "ar", "nat_name": "Argentina", "sofifa": 223345},
        {"name": "L. Messi", "pos": "FW", "nat": "ar", "nat_name": "Argentina", "sofifa": 158023},
        {"name": "L. Martínez", "pos": "FW", "nat": "ar", "nat_name": "Argentina", "sofifa": 248414},
        {"name": "P. Dybala", "pos": "FW", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "J. Álvarez", "pos": "FW", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "M. Acuña", "pos": "DF", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "A. Mac Allister", "pos": "MF", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "C. Romero", "pos": "DF", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "Á. Di María", "pos": "FW", "nat": "ar", "nat_name": "Argentina", "sofifa": 0},
        {"name": "R. De Paul", "pos": "MF", "nat": "ar", "nat_name": "Argentina", "sofifa": 215528},
    ],
    "Venezuela": [
        {"name": "R. Romo", "pos": "GK", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "Y. Herrera", "pos": "MF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "D. Machís", "pos": "FW", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "J. Martinez", "pos": "MF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "J. Martinez", "pos": "MF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "C. Cásseres Jr", "pos": "MF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "M. Villanueva", "pos": "MF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "J. Cádiz", "pos": "DF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "L. Gonzalez", "pos": "DF", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
        {"name": "J. Moreno", "pos": "FW", "nat": "ve", "nat_name": "Venezuela", "sofifa": 0},
    ],
    "Bolivia": [
        {"name": "C. Lampe", "pos": "GK", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "S. Galindo", "pos": "DF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "M. Enoumba", "pos": "DF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "H. Vaca", "pos": "MF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "A. Jusino", "pos": "DF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "J. Arrascaita", "pos": "MF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "A. Quiroga", "pos": "MF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "D. Mancilla", "pos": "FW", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "J. Chura", "pos": "FW", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
        {"name": "J. Sagredo", "pos": "MF", "nat": "bo", "nat_name": "Bolivia", "sofifa": 0},
    ],
    "Germany": [
        {"name": "M. ter Stegen", "pos": "GK", "nat": "de", "nat_name": "Alemania", "sofifa": 192448},
        {"name": "K. Havertz", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "J. Musiala", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "İ. Gündoğan", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "F. Wirtz", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "J. Kimmich", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "S. Gnabry", "pos": "FW", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "L. Sané", "pos": "FW", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "A. Rüdiger", "pos": "DF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
        {"name": "J. Brandt", "pos": "MF", "nat": "de", "nat_name": "Alemania", "sofifa": 0},
    ],
    "England": [
        {"name": "N. Pope", "pos": "GK", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 205600},
        {"name": "P. Foden", "pos": "MF", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 237692},
        {"name": "M. Rashford", "pos": "FW", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
        {"name": "J. Bellingham", "pos": "MF", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 246669},
        {"name": "T. Alexander-Arnold", "pos": "DF", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
        {"name": "B. Saka", "pos": "FW", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
        {"name": "D. Rice", "pos": "MF", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
        {"name": "H. Kane", "pos": "FW", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 202126},
        {"name": "C. Palmer", "pos": "MF", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
        {"name": "R. Sterling", "pos": "FW", "nat": "gb-eng", "nat_name": "Inglaterra", "sofifa": 0},
    ],
    "Norway": [
        {"name": "Ø. Nyland", "pos": "GK", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "E. Haaland", "pos": "FW", "nat": "no", "nat_name": "Noruega", "sofifa": 239085},
        {"name": "M. Ødegaard", "pos": "MF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "F. Aursnes", "pos": "MF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "A. Sørloth", "pos": "FW", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "J. Ryerson", "pos": "DF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "K. Ajer", "pos": "DF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "P. Berg", "pos": "MF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "A. Pellegrino", "pos": "DF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
        {"name": "J. Svensson", "pos": "DF", "nat": "no", "nat_name": "Noruega", "sofifa": 0},
    ],
    "USA": [
        {"name": "M. Turner", "pos": "GK", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "C. Pulisic", "pos": "MF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "G. Reyna", "pos": "MF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "W. McKennie", "pos": "MF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "S. Dest", "pos": "DF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "F. Balogun", "pos": "FW", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "A. Robinson", "pos": "DF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "T. Adams", "pos": "MF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "C. Carter-Vickers", "pos": "DF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
        {"name": "J. Brooks", "pos": "DF", "nat": "us", "nat_name": "EE.UU.", "sofifa": 0},
    ],
    "Costa Rica": [
        {"name": "K. Navas", "pos": "GK", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "J. Vargas", "pos": "MF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "O. Duarte", "pos": "DF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "C. Gamboa", "pos": "DF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "R. Leal", "pos": "FW", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "F. Brown Forbes", "pos": "MF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "J. Cascante", "pos": "DF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "K. Vargas", "pos": "FW", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "D. Chacón", "pos": "MF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
        {"name": "A. Martínez", "pos": "MF", "nat": "cr", "nat_name": "Costa Rica", "sofifa": 0},
    ],
    "Qatar": [
        {"name": "M. Barsham", "pos": "GK", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "A. Afif", "pos": "FW", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "A. Ali", "pos": "MF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "K. Boudiaf", "pos": "MF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "H. Al Haydos", "pos": "MF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "A. Hatem", "pos": "MF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "B. Khoukhi", "pos": "DF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "Lucas Mendes", "pos": "DF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "A. Asad", "pos": "DF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
        {"name": "H. Ahmed", "pos": "MF", "nat": "qa", "nat_name": "Qatar", "sofifa": 0},
    ],
    "Australia": [
        {"name": "M. Ryan", "pos": "GK", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "C. Goodwin", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "J. Irvine", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "M. Leckie", "pos": "FW", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "R. McGree", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "A. Grant", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "H. Souttar", "pos": "DF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "M. Luongo", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "C. Devlin", "pos": "MF", "nat": "au", "nat_name": "Australia", "sofifa": 0},
        {"name": "J. Maclaren", "pos": "FW", "nat": "au", "nat_name": "Australia", "sofifa": 0},
    ],
    "Morocco": [
        {"name": "Y. Bounou", "pos": "GK", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "A. Hakimi", "pos": "DF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "Y. En-Nesyri", "pos": "FW", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "Brahim", "pos": "MF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "N. Mazraoui", "pos": "DF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "H. Ziyech", "pos": "MF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "S. Amrabat", "pos": "MF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "Munir", "pos": "FW", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "A. Adli", "pos": "MF", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
        {"name": "A. Ezzalzouli", "pos": "FW", "nat": "ma", "nat_name": "Marruecos", "sofifa": 0},
    ],
    "Egypt": [
        {"name": "K. Eissa", "pos": "GK", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "M. Salah", "pos": "FW", "nat": "eg", "nat_name": "Egipto", "sofifa": 209331},
        {"name": "Marmoush", "pos": "FW", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "A. Hegazi", "pos": "DF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "Trezeguet", "pos": "FW", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "M. Mohamed", "pos": "MF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "T. Hamed", "pos": "MF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "M. Elneny", "pos": "MF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "M. Morsy", "pos": "MF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
        {"name": "A. Hassan", "pos": "MF", "nat": "eg", "nat_name": "Egipto", "sofifa": 0},
    ],
    "Senegal": [
        {"name": "É. Mendy", "pos": "GK", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "S. Mané", "pos": "FW", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "K. Koulibaly", "pos": "DF", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "B. Dia", "pos": "FW", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "P. Sarr", "pos": "MF", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "M. Niakhaté", "pos": "DF", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "N. Jackson", "pos": "FW", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "Y. Sabaly", "pos": "DF", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "I. Gueye", "pos": "MF", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
        {"name": "I. Sarr", "pos": "FW", "nat": "sn", "nat_name": "Senegal", "sofifa": 0},
    ],
    "Sweden": [
        {"name": "R. Olsen", "pos": "GK", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "A. Isak", "pos": "FW", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "D. Kulusevski", "pos": "FW", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "V. Gyökeres", "pos": "FW", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "E. Forsberg", "pos": "MF", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "V. Lindelöf", "pos": "DF", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "M. Svanberg", "pos": "MF", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "J. Karlsson", "pos": "MF", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "K. Olsson", "pos": "DF", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
        {"name": "H. Larsson", "pos": "FW", "nat": "se", "nat_name": "Suecia", "sofifa": 0},
    ],
    "Serbia": [
        {"name": "V. Milinković-Savić", "pos": "GK", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "S. Milinković-Savić", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "D. Vlahović", "pos": "FW", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "F. Kostić", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "D. Tadić", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "A. Mitrović", "pos": "FW", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "N. Gudelj", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "N. Matić", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "N. Milenković", "pos": "DF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
        {"name": "M. Milovanović", "pos": "MF", "nat": "rs", "nat_name": "Serbia", "sofifa": 0},
    ],
    "Wales": [
        {"name": "W. Hennessey", "pos": "GK", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "B. Johnson", "pos": "DF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "B. Davies", "pos": "DF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "J. Rodon", "pos": "DF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "E. Ampadu", "pos": "MF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "D. Brooks", "pos": "MF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "H. Wilson", "pos": "MF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "C. Roberts", "pos": "MF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "D. James", "pos": "FW", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
        {"name": "L. Harris", "pos": "MF", "nat": "gb-wls", "nat_name": "Gales", "sofifa": 0},
    ],
    "Scotland": [
        {"name": "A. Gunn", "pos": "GK", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "A. Robertson", "pos": "DF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "K. Tierney", "pos": "DF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "J. McGinn", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "C. McGregor", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "S. McTominay", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "R. Gauld", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "L. Ferguson", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "T. Cairney", "pos": "MF", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
        {"name": "B. Doak", "pos": "FW", "nat": "gb-sct", "nat_name": "Escocia", "sofifa": 0},
    ],
    "Belgium": [
        {"name": "T. Courtois", "pos": "GK", "nat": "be", "nat_name": "Bélgica", "sofifa": 192119},
        {"name": "K. De Bruyne", "pos": "MF", "nat": "be", "nat_name": "Bélgica", "sofifa": 192985},
        {"name": "Y. Carrasco", "pos": "MF", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "R. Lukaku", "pos": "FW", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "L. Openda", "pos": "FW", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "L. Trossard", "pos": "FW", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "J. Doku", "pos": "FW", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "Y. Tielemans", "pos": "MF", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "A. Witsel", "pos": "MF", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
        {"name": "A. Vermeeren", "pos": "MF", "nat": "be", "nat_name": "Bélgica", "sofifa": 0},
    ],
    "Colombia": [
        {"name": "Á. Montero", "pos": "GK", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "L. Díaz", "pos": "FW", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "D. Muñoz", "pos": "DF", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "L. Muriel", "pos": "FW", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "L. Sinisterra", "pos": "FW", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "J. Quintero", "pos": "MF", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "J. Mojica", "pos": "DF", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "D. Silva", "pos": "MF", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "D. Cataño", "pos": "MF", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
        {"name": "Y. Asprilla", "pos": "FW", "nat": "co", "nat_name": "Colombia", "sofifa": 0},
    ],
    "Chile": [
        {"name": "C. Bravo", "pos": "GK", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "A. Sánchez", "pos": "FW", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "G. Maripán", "pos": "DF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "A. Vidal", "pos": "MF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "P. Díaz", "pos": "DF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "B. Brereton Díaz", "pos": "FW", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "E. Bolindos", "pos": "MF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "R. Echeverría", "pos": "MF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "C. Palacios", "pos": "MF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
        {"name": "D. Pizarro", "pos": "MF", "nat": "cl", "nat_name": "Chile", "sofifa": 0},
    ],
    "Peru": [
        {"name": "P. Gallese", "pos": "GK", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "R. Tapia", "pos": "MF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "L. Advíncula", "pos": "DF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "R. Ruidíaz", "pos": "FW", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "A. Callens", "pos": "DF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "G. Lapadula", "pos": "FW", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "C. Cueva", "pos": "MF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "P. Guerrero", "pos": "FW", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "A. Polo", "pos": "MF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
        {"name": "A. Valera", "pos": "DF", "nat": "pe", "nat_name": "Perú", "sofifa": 0},
    ],
    "Jamaica": [
        {"name": "A. Blake", "pos": "GK", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "L. Bailey", "pos": "FW", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "E. Pinnock", "pos": "DF", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "M. Antonio", "pos": "FW", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "D. Gray", "pos": "DF", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "B. Cordova", "pos": "MF", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "K. Roofe", "pos": "FW", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "S. Nicholson", "pos": "FW", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "A. Bell", "pos": "DF", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
        {"name": "O. Hutchinson", "pos": "FW", "nat": "jm", "nat_name": "Jamaica", "sofifa": 0},
    ],
    "Canada": [
        {"name": "M. Crépeau", "pos": "GK", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "A. Davies", "pos": "DF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "J. David", "pos": "FW", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "S. Eustáquio", "pos": "MF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "C. Larin", "pos": "FW", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "A. Johnston", "pos": "MF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "J. Osorio", "pos": "MF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "T. Buchanan", "pos": "MF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "L. Millar", "pos": "MF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
        {"name": "N. Saliba", "pos": "DF", "nat": "ca", "nat_name": "Canadá", "sofifa": 0},
    ],
    "Hungary": [
        {"name": "P. Gulácsi", "pos": "GK", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "W. Orban", "pos": "DF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "D. Szoboszlai", "pos": "MF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "R. Sallai", "pos": "FW", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "M. Kerkez", "pos": "DF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "D. Gazdag", "pos": "MF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "B. Varga", "pos": "FW", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "Z. Kalmár", "pos": "MF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "D. Sallói", "pos": "FW", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
        {"name": "K. Lisztes", "pos": "MF", "nat": "hu", "nat_name": "Hungría", "sofifa": 0},
    ],
    "Netherlands": [
        {"name": "M. Flekken", "pos": "GK", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "V. van Dijk", "pos": "DF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "F. de Jong", "pos": "MF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "J. Frimpong", "pos": "DF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "M. de Ligt", "pos": "DF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "D. Malen", "pos": "FW", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "M. Depay", "pos": "FW", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "C. Gakpo", "pos": "FW", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "X. Simons", "pos": "MF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
        {"name": "J. Hato", "pos": "DF", "nat": "nl", "nat_name": "Países Bajos", "sofifa": 0},
    ],
    "France": [
        {"name": "M. Maignan", "pos": "GK", "nat": "fr", "nat_name": "Francia", "sofifa": 218401},
        {"name": "K. Mbappé", "pos": "FW", "nat": "fr", "nat_name": "Francia", "sofifa": 231747},
        {"name": "K. Benzema", "pos": "FW", "nat": "fr", "nat_name": "Francia", "sofifa": 165153},
        {"name": "A. Griezmann", "pos": "FW", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "J. Koundé", "pos": "DF", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "K. Coman", "pos": "FW", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "N. Kanté", "pos": "MF", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "T. Hernández", "pos": "DF", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "C. Nkunku", "pos": "FW", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
        {"name": "W. Zaïre-Emery", "pos": "MF", "nat": "fr", "nat_name": "Francia", "sofifa": 0},
    ],
    "Japan": [
        {"name": "K. Nakamura", "pos": "GK", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "D. Kamada", "pos": "MF", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "K. Mitoma", "pos": "FW", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "T. Kubo", "pos": "FW", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "W. Endo", "pos": "MF", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "H. Morita", "pos": "MF", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "T. Minamino", "pos": "FW", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "J. Ito", "pos": "FW", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "R. Doan", "pos": "MF", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
        {"name": "K. Sano", "pos": "MF", "nat": "jp", "nat_name": "Japón", "sofifa": 0},
    ],
    "Israel": [
        {"name": "D. Peretz", "pos": "GK", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "M. Solomon", "pos": "MF", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "M. Abu Fani", "pos": "MF", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "S. Weissman", "pos": "FW", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "O. Gloukh", "pos": "MF", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "L. Abada", "pos": "FW", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "O. Atzili", "pos": "FW", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "R. Safuri", "pos": "MF", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "T. Baribo", "pos": "FW", "nat": "il", "nat_name": "Israel", "sofifa": 0},
        {"name": "O. Gandelman", "pos": "FW", "nat": "il", "nat_name": "Israel", "sofifa": 0},
    ],
    "Nigeria": [
        {"name": "M. Okoye", "pos": "GK", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "V. Osimhen", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "A. Lookman", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "V. Boniface", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "S. Chukwueze", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "W. Ndidi", "pos": "MF", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "T. Moffi", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "T. Awoniyi", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "A. Nwakaeme", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
        {"name": "S. Nwankwo", "pos": "FW", "nat": "ng", "nat_name": "Nigeria", "sofifa": 0},
    ],
    "Cameroon": [
        {"name": "A. Onana", "pos": "GK", "nat": "cm", "nat_name": "Camerún", "sofifa": 224334},
        {"name": "A. Zambo Anguissa", "pos": "MF", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "J. Matip", "pos": "DF", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "B. Mbeumo", "pos": "FW", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "V. Aboubakar", "pos": "FW", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "E. Choupo-Moting", "pos": "FW", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "G. Nkoudou", "pos": "FW", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "H. Moukoudi", "pos": "DF", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "K. Toko Ekambi", "pos": "FW", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
        {"name": "C. Baleba", "pos": "MF", "nat": "cm", "nat_name": "Camerún", "sofifa": 0},
    ],
    "Ivory Coast": [
        {"name": "Y. Fofana", "pos": "MF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "F. Kessié", "pos": "MF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "S. Fofana", "pos": "DF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "W. Zaha", "pos": "FW", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "S. Haller", "pos": "FW", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "I. Sangaré", "pos": "MF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "O. Kossounou", "pos": "DF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "N. Pépé", "pos": "FW", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "C. Kouamé", "pos": "FW", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
        {"name": "A. Diallo", "pos": "DF", "nat": "ci", "nat_name": "Costa de Marfil", "sofifa": 0},
    ],
    "Algeria": [
        {"name": "A. Oukidja", "pos": "GK", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "R. Mahrez", "pos": "FW", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "I. Bennacer", "pos": "MF", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "N. Bentaleb", "pos": "MF", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "A. Gouiri", "pos": "FW", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "R. Bensebaini", "pos": "DF", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "S. Benrahma", "pos": "FW", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "R. Ghezzal", "pos": "FW", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "F. Chaïbi", "pos": "MF", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
        {"name": "B. Bouanani", "pos": "FW", "nat": "dz", "nat_name": "Argelia", "sofifa": 0},
    ],
}

# ---------------------------------------------------------------------------
# RANKING INICIAL FIFA
# ---------------------------------------------------------------------------
INITIAL_FIFA_RANKING = {
    "France": 1840, "Spain": 1810, "England": 1780, "Germany": 1750,
    "Portugal": 1720, "Italy": 1690, "Netherlands": 1650, "Belgium": 1620,
    "Croatia": 1580, "Denmark": 1560, "Switzerland": 1530, "Norway": 1480,
    "Austria": 1450, "Sweden": 1420, "Poland": 1390, "Serbia": 1360,
    "Turkey": 1330, "Ukraine": 1310, "Czech Republic": 1280, "Greece": 1250,
    "Scotland": 1220, "Wales": 1200, "Iceland": 1150, "Hungary": 1180,
    "Israel": 1200,
    "Argentina": 1870, "Brazil": 1830, "Colombia": 1650, "Uruguay": 1620,
    "Chile": 1540, "Ecuador": 1510, "Paraguay": 1430, "Peru": 1380,
    "Bolivia": 1250, "Venezuela": 1230,
    "Senegal": 1630, "Morocco": 1600, "Tunisia": 1530, "Ghana": 1480,
    "Egypt": 1450, "Ivory Coast": 1440, "Nigeria": 1420, "Cameroon": 1390,
    "South Africa": 1330, "Algeria": 1350,
    "Mexico": 1550, "USA": 1530, "Canada": 1490, "Costa Rica": 1380,
    "Panama": 1360, "Jamaica": 1280,
    "Japan": 1560, "Korea": 1530, "Australia": 1470, "Saudi Arabia": 1420,
    "Iran": 1440, "Qatar": 1370,
    "New Zealand": 1100,
}

# ---------------------------------------------------------------------------
# MAPA DE CÓDIGOS ISO PARA BANDERAS
# ---------------------------------------------------------------------------
COUNTRY_CODES = {
    "France": "FR", "Spain": "ES", "England": "ENG", "Germany": "DE",
    "Portugal": "PT", "Italy": "IT", "Netherlands": "NL", "Belgium": "BE",
    "Croatia": "HR", "Denmark": "DK", "Switzerland": "CH", "Norway": "NO",
    "Austria": "AT", "Sweden": "SE", "Poland": "PL", "Serbia": "RS",
    "Turkey": "TR", "Ukraine": "UA", "Czech Republic": "CZ", "Greece": "GR",
    "Scotland": "SCO", "Wales": "WAL", "Iceland": "IS", "Hungary": "HU",
    "Israel": "IL", "Argentina": "AR", "Brazil": "BR", "Colombia": "CO",
    "Uruguay": "UY", "Chile": "CL", "Ecuador": "EC", "Paraguay": "PY",
    "Peru": "PE", "Bolivia": "BO", "Venezuela": "VE", "Senegal": "SN",
    "Morocco": "MA", "Tunisia": "TN", "Ghana": "GH", "Egypt": "EG",
    "Ivory Coast": "CI", "Nigeria": "NG", "Cameroon": "CM", "South Africa": "ZA",
    "Algeria": "DZ", "Mexico": "MX", "USA": "US", "Canada": "CA",
    "Costa Rica": "CR", "Panama": "PA", "Jamaica": "JM", "Japan": "JP",
    "Korea": "KR", "Australia": "AU", "Saudi Arabia": "SA", "Iran": "IR",
    "Qatar": "QA", "New Zealand": "NZ"
}

# ---------------------------------------------------------------------------
# FUNCIÓN PARA OBTENER URL DE BANDERA (CORREGIDA)
# ---------------------------------------------------------------------------
def get_flag_url(country_name, size=16):
    """
    Devuelve URL de imagen de bandera de flagcdn.com
    
    Args:
        country_name (str): Nombre del país
        size (int): Tamaño de la imagen (ancho en píxeles)
    
    Returns:
        str: URL de la imagen o string vacío si no encuentra
    """
    code = COUNTRY_CODES.get(country_name, "").lower()
    
    # Convertir códigos especiales para flagcdn.com
    if code == "eng":
        code = "gb-eng"
    elif code == "sco":
        code = "gb-sct"
    elif code == "wal":
        code = "gb-wls"
    
    if code:
        return f"https://flagcdn.com/{size}x12/{code}.png"
    return ""

# ---------------------------------------------------------------------------
# FUNCIÓN PARA GENERAR HTML DE BANDERA (RECOMENDADA PARA STREAMLIT)
# ---------------------------------------------------------------------------
def get_flag_html(country_name, size=16, show_name=True):
    """
    Genera HTML para mostrar bandera y nombre del país
    
    Args:
        country_name (str): Nombre del país
        size (int): Tamaño de la bandera
        show_name (bool): Si muestra el nombre del país
    
    Returns:
        str: HTML listo para usar en st.markdown
    """
    flag_url = get_flag_url(country_name, size)
    
    if flag_url:
        html = f'''
        <div style="display:flex; align-items:center; gap:8px;">
            <img src="{flag_url}" 
                 style="vertical-align:middle; border-radius:3px; width:{size}px; height:auto;">
            {f'<span>{country_name}</span>' if show_name else ''}
        </div>
        '''
    else:
        html = f'<span>{country_name}</span>'
    
    return html
