"""
data.py - Base de datos del simulador MMJ World Cup
Flags para England/Scotland/Wales usan secuencias escapadas para evitar
caracteres bidireccionales ocultos (warning de GitHub).
"""

UEFA_TEAMS = [
    "Switzerland", "Denmark", "Poland", "Austria", "Croatia",
    "Sweden", "Serbia", "Wales", "Scotland", "Belgium",
    "Ukraine", "Czech Republic", "Iceland", "Greece", "Turkey",
    "Norway", "Netherlands", "France", "Spain", "Portugal",
    "Italy", "England", "Germany", "Russia",
]
CONMEBOL_TEAMS = [
    "Brazil", "Argentina", "Colombia", "Chile", "Peru",
    "Uruguay", "Venezuela", "Bolivia", "Paraguay", "Ecuador",
]
CAF_TEAMS = [
    "South Africa", "Morocco", "Tunisia", "Ghana", "Senegal",
    "Egypt", "Ivory Coast", "Cameroon", "Nigeria", "Algeria",
]
CONCACAF_TEAMS = ["Mexico", "Panama", "Costa Rica", "USA", "Canada", "Jamaica"]
AFC_TEAMS = ["Korea", "Saudi Arabia", "Japan", "Australia", "Iran", "Qatar"]
PLAYOFF_TEAMS = ["New Zealand"]

ALL_TEAMS = UEFA_TEAMS + CONMEBOL_TEAMS + CAF_TEAMS + CONCACAF_TEAMS + AFC_TEAMS + PLAYOFF_TEAMS
COPA_AMERICA_GUESTS_POOL = CONCACAF_TEAMS + AFC_TEAMS + CAF_TEAMS + PLAYOFF_TEAMS

# ---------------------------------------------------------------------------
# JUGADORES  (basados en la imagen de plantillas recibida)
# Cada equipo tiene sus propios jugadores, sin mezclas.
# ---------------------------------------------------------------------------
PLAYERS = {
    # ── UEFA ─────────────────────────────────────────────────────────────────
    "Ukraine": [
        {"name": "V. Tsygankov",    "position": "MF"},
        {"name": "O. Zinchenko",    "position": "DF"},
        {"name": "R. Malinovskyi", "position": "MF"},
        {"name": "T. Stepanenko",  "position": "MF"},
        {"name": "Y. Rakitskyi",   "position": "DF"},
        {"name": "M. Shaparenko",  "position": "MF"},
        {"name": "A. Lunin",       "position": "GK"},
        {"name": "V. Buyalskyi",   "position": "MF"},
        {"name": "M. Matviienko",  "position": "DF"},
        {"name": "M. Mudryk",      "position": "FW"},
        {"name": "J. Pavlenka",    "position": "GK"},
        {"name": "V. Coufal",      "position": "DF"},
        {"name": "T. Holes",       "position": "MF"},
        {"name": "K. Krejci",      "position": "MF"},
        {"name": "J. Porsteinsson","position": "DF"},
        {"name": "J. Pavlenka",    "position": "GK"},
        {"name": "V. Cerny",       "position": "FW"},
        {"name": "M. Jurasek",     "position": "DF"},
        {"name": "J. Milinkovics-Savic","position": "GK"},
        {"name": "J. Milinkovics-Savic","position": "GK"},
        {"name": "N. Milenkovics-Savic","position": "GK"},
        {"name": "R. Olsen",       "position": "GK"},
        {"name": "A. Isak",        "position": "FW"},
        {"name": "D. Kulusevski",  "position": "FW"},
        {"name": "V. Gyokeres",    "position": "FW"},
        {"name": "E. Forsberg",    "position": "MF"},
        {"name": "V. Lindelof",    "position": "DF"},
    ],
    "Czech Republic": [
        {"name": "P. Schick",       "position": "FW"},
        {"name": "T. Soucek",       "position": "MF"},
        {"name": "V. Coufal",       "position": "DF"},
        {"name": "A. Hlozek",       "position": "FW"},
        {"name": "T. Holes",        "position": "MF"},
        {"name": "J. Gudmundsson",  "position": "MF"},
        {"name": "M. Anderson",     "position": "MF"},
        {"name": "H. Haraldsson",   "position": "MF"},
        {"name": "K. Hlynsson",     "position": "MF"},
        {"name": "B. Sigurdsson",   "position": "MF"},
        {"name": "J. Porsteinsson", "position": "DF"},
        {"name": "R. Magnusson",    "position": "DF"},
        {"name": "K. Tsimikas",     "position": "DF"},
        {"name": "A. Sigurdsson",   "position": "MF"},
        {"name": "J. Pavlenka",     "position": "GK"},
        {"name": "V. Cerny",        "position": "FW"},
        {"name": "M. Jurasek",      "position": "DF"},
    ],
    "Iceland": [
        {"name": "S. Ingason",       "position": "DF"},
        {"name": "A. Gudmundsson",   "position": "MF"},
        {"name": "H. Magnusson",     "position": "DF"},
        {"name": "K. Tsimikas",      "position": "DF"},
        {"name": "A. Sigurdsson",    "position": "MF"},
        {"name": "J. Gudmundsson",   "position": "MF"},
        {"name": "M. Anderson",      "position": "MF"},
        {"name": "H. Haraldsson",    "position": "MF"},
        {"name": "K. Hlynsson",      "position": "MF"},
        {"name": "R. Runnarsson",    "position": "GK"},
        {"name": "W. Hennessey",     "position": "GK"},
        {"name": "B. Sigurdsson",    "position": "MF"},
        {"name": "G. Sigurdsson",    "position": "MF"},
        {"name": "A. Gudjohnsen",    "position": "FW"},
        {"name": "I. Gunnarsson",    "position": "MF"},
        {"name": "G. Gunnarsson",    "position": "DF"},
        {"name": "E. Bodvarsson",    "position": "FW"},
    ],
    "Greece": [
        {"name": "O. Vlachodimos",   "position": "GK"},
        {"name": "K. Mavropanos",    "position": "DF"},
        {"name": "V. Pavlidis",      "position": "FW"},
        {"name": "K. Tsimikas",      "position": "DF"},
        {"name": "A. Bakasetas",     "position": "MF"},
        {"name": "T. Fountis",       "position": "MF"},
        {"name": "T. Douvikas",      "position": "FW"},
        {"name": "G. Giakoumakis",   "position": "FW"},
        {"name": "G. Koutsias",      "position": "FW"},
        {"name": "D. Stankovic",     "position": "DF"},
        {"name": "C. Stankovic",     "position": "DF"},
        {"name": "K. Danso",         "position": "DF"},
        {"name": "I. Rakitic",       "position": "MF"},
        {"name": "L. Majer",         "position": "MF"},
        {"name": "G. Gauld",         "position": "MF"},
        {"name": "A. Robertson",     "position": "DF"},
        {"name": "J. McGinn",        "position": "MF"},
    ],
    "Turkey": [
        {"name": "H. Calhanoglu",    "position": "MF"},
        {"name": "K. Kokcu",         "position": "MF"},
        {"name": "E. Unal",          "position": "FW"},
        {"name": "U. Cakir",         "position": "GK"},
        {"name": "S. Ozcan",         "position": "MF"},
        {"name": "K. Aktuerkoeglu",  "position": "FW"},
        {"name": "A. Bardakci",      "position": "DF"},
        {"name": "M. Demiral",       "position": "DF"},
        {"name": "A. Guler",         "position": "MF"},
        {"name": "D. Livakovic",     "position": "GK"},
        {"name": "M. Kovacic",       "position": "MF"},
        {"name": "M. Pasalic",       "position": "MF"},
        {"name": "J. Gvardiol",      "position": "DF"},
        {"name": "M. Brozovic",      "position": "MF"},
        {"name": "L. Modric",        "position": "MF"},
        {"name": "A. Kramaric",      "position": "FW"},
        {"name": "J. Courtois",      "position": "GK"},
    ],
    "Switzerland": [
        {"name": "G. Kobel",        "position": "GK"},
        {"name": "G. Xhaka",        "position": "MF"},
        {"name": "M. Akanji",       "position": "DF"},
        {"name": "F. Schar",        "position": "DF"},
        {"name": "R. Freuler",      "position": "MF"},
        {"name": "B. Embolo",       "position": "FW"},
        {"name": "N. Okafor",       "position": "FW"},
        {"name": "D. Zakaria",      "position": "MF"},
        {"name": "B. Rodriguez",    "position": "FW"},
        {"name": "N. Elvedi",       "position": "DF"},
        {"name": "X. Shaqiri",      "position": "MF"},
        {"name": "Y. Sow",          "position": "MF"},
        {"name": "K. Schmeichel",   "position": "GK"},
        {"name": "A. Christensen",  "position": "DF"},
        {"name": "P. Hojbjerg",     "position": "MF"},
        {"name": "S. Kjaer",        "position": "DF"},
        {"name": "M. Hjulmand",     "position": "MF"},
        {"name": "R. Hojlund",      "position": "FW"},
        {"name": "C. Eriksen",      "position": "MF"},
        {"name": "N. O'Riley",      "position": "MF"},
        {"name": "J. Andersen",     "position": "DF"},
    ],
    "Denmark": [
        {"name": "K. Schmeichel",   "position": "GK"},
        {"name": "A. Christensen",  "position": "DF"},
        {"name": "P. Hojbjerg",     "position": "MF"},
        {"name": "S. Kjaer",        "position": "DF"},
        {"name": "M. Hjulmand",     "position": "MF"},
        {"name": "R. Hojlund",      "position": "FW"},
        {"name": "C. Eriksen",      "position": "MF"},
        {"name": "N. O'Riley",      "position": "MF"},
        {"name": "J. Andersen",     "position": "DF"},
        {"name": "M. Damsgaard",    "position": "MF"},
        {"name": "W. Szczepny",     "position": "GK"},
        {"name": "R. Lewandowski",  "position": "FW"},
        {"name": "P. Zielinski",    "position": "MF"},
        {"name": "J. Bednarek",     "position": "DF"},
        {"name": "P. Frankowski",   "position": "DF"},
        {"name": "S. Szymanski",    "position": "MF"},
        {"name": "A. Milik",        "position": "FW"},
        {"name": "J. Kiwior",       "position": "DF"},
        {"name": "M. Cash",         "position": "DF"},
    ],
    "Poland": [
        {"name": "W. Szczepny",      "position": "GK"},
        {"name": "R. Lewandowski",   "position": "FW"},
        {"name": "P. Zielinski",     "position": "MF"},
        {"name": "J. Bednarek",      "position": "DF"},
        {"name": "P. Frankowski",    "position": "DF"},
        {"name": "S. Szymanski",     "position": "MF"},
        {"name": "A. Milik",         "position": "FW"},
        {"name": "J. Kiwior",        "position": "DF"},
        {"name": "M. Cash",          "position": "DF"},
        {"name": "J. Zalewski",      "position": "MF"},
        {"name": "S. Stankovic",     "position": "DF"},
        {"name": "C. Stankovic",     "position": "DF"},
        {"name": "D. Alaba",         "position": "DF"},
        {"name": "K. Laimer",        "position": "MF"},
        {"name": "M. Sabitzer",      "position": "MF"},
        {"name": "M. Gregoritsch",   "position": "FW"},
        {"name": "X. Schlager",      "position": "MF"},
        {"name": "A. Arnautovic",    "position": "FW"},
        {"name": "K. Danso",         "position": "DF"},
    ],
    "Austria": [
        {"name": "P. Pentz",         "position": "GK"},
        {"name": "D. Alaba",         "position": "DF"},
        {"name": "K. Laimer",        "position": "MF"},
        {"name": "M. Sabitzer",      "position": "MF"},
        {"name": "M. Gregoritsch",   "position": "FW"},
        {"name": "X. Schlager",      "position": "MF"},
        {"name": "A. Arnautovic",    "position": "FW"},
        {"name": "K. Danso",         "position": "DF"},
        {"name": "A. Kramaric",      "position": "FW"},
        {"name": "A. Vermeeren",     "position": "MF"},
        {"name": "D. Livakovic",     "position": "GK"},
        {"name": "L. Modric",        "position": "MF"},
        {"name": "M. Kovacic",       "position": "MF"},
        {"name": "J. Gvardiol",      "position": "DF"},
        {"name": "M. Brozovic",      "position": "MF"},
        {"name": "M. Pasalic",       "position": "MF"},
        {"name": "N. Vlasic",        "position": "FW"},
        {"name": "L. Majer",         "position": "MF"},
        {"name": "J. Rakitic",       "position": "MF"},
        {"name": "I. Perisic",       "position": "FW"},
    ],
    "Croatia": [
        {"name": "D. Livakovic",     "position": "GK"},
        {"name": "L. Modric",        "position": "MF"},
        {"name": "I. Perisic",       "position": "FW"},
        {"name": "J. Gvardiol",      "position": "DF"},
        {"name": "M. Kovacic",       "position": "MF"},
        {"name": "A. Kramaric",      "position": "FW"},
        {"name": "M. Brozovic",      "position": "MF"},
        {"name": "M. Pasalic",       "position": "MF"},
        {"name": "N. Vlasic",        "position": "FW"},
        {"name": "L. Majer",         "position": "MF"},
        {"name": "J. Gvardiol",      "position": "DF"},
        {"name": "L. Trossard",      "position": "FW"},
        {"name": "Y. Carrasco",      "position": "MF"},
        {"name": "J. Doku",          "position": "FW"},
        {"name": "A. Witsel",        "position": "MF"},
        {"name": "A. Vermeeren",     "position": "MF"},
        {"name": "K. De Bruyne",     "position": "MF"},
        {"name": "T. Courtois",      "position": "GK"},
        {"name": "R. Lukaku",        "position": "FW"},
        {"name": "L. Openda",        "position": "FW"},
    ],
    "Sweden": [
        {"name": "R. Olsen",         "position": "GK"},
        {"name": "A. Isak",          "position": "FW"},
        {"name": "D. Kulusevski",    "position": "FW"},
        {"name": "V. Gyokeres",      "position": "FW"},
        {"name": "E. Forsberg",      "position": "MF"},
        {"name": "V. Lindelof",      "position": "DF"},
        {"name": "M. Svanberg",      "position": "MF"},
        {"name": "K. Karlsson",      "position": "MF"},
        {"name": "K. Olsson",        "position": "GK"},
        {"name": "H. Larsson",       "position": "MF"},
        {"name": "J. Milinkovics-Savic","position": "GK"},
        {"name": "D. Vlahovic",      "position": "FW"},
        {"name": "F. Kostic",        "position": "MF"},
        {"name": "S. Milinkovics-Savic","position": "MF"},
        {"name": "N. Gudelj",        "position": "MF"},
        {"name": "N. Milenkovic",    "position": "DF"},
        {"name": "N. Matic",         "position": "MF"},
        {"name": "D. Tadici",        "position": "DF"},
        {"name": "A. Mitrovic",      "position": "FW"},
    ],
    "Serbia": [
        {"name": "V. Milinkovic-Savic","position": "GK"},
        {"name": "S. Milinkovic-Savic","position": "MF"},
        {"name": "D. Vlahovic",      "position": "FW"},
        {"name": "N. Gudelj",        "position": "MF"},
        {"name": "A. Mitrovic",      "position": "FW"},
        {"name": "F. Kostic",        "position": "MF"},
        {"name": "N. Milenkovic",    "position": "DF"},
        {"name": "N. Matic",         "position": "MF"},
        {"name": "D. Tadici",        "position": "DF"},
        {"name": "W. Hennessey",     "position": "GK"},
        {"name": "D. James",         "position": "FW"},
        {"name": "E. Ampadu",        "position": "MF"},
        {"name": "B. Davies",        "position": "DF"},
        {"name": "H. Wilson",        "position": "MF"},
        {"name": "C. Roberts",       "position": "DF"},
        {"name": "J. Rodon",         "position": "DF"},
        {"name": "L. Harris",        "position": "DF"},
    ],
    "Wales": [
        {"name": "W. Hennessey",     "position": "GK"},
        {"name": "D. James",         "position": "FW"},
        {"name": "E. Ampadu",        "position": "MF"},
        {"name": "B. Davies",        "position": "DF"},
        {"name": "H. Wilson",        "position": "MF"},
        {"name": "C. Roberts",       "position": "DF"},
        {"name": "J. Rodon",         "position": "DF"},
        {"name": "L. Harris",        "position": "DF"},
        {"name": "S. Brooks",        "position": "FW"},
        {"name": "D. Brooks",        "position": "FW"},
        {"name": "L. Moore",         "position": "FW"},
        {"name": "T. Cabango",       "position": "DF"},
        {"name": "B. Johnson",       "position": "MF"},
    ],
    "Scotland": [
        {"name": "A. Gunn",          "position": "GK"},
        {"name": "A. Robertson",     "position": "DF"},
        {"name": "S. McTominay",     "position": "MF"},
        {"name": "J. McGinn",        "position": "MF"},
        {"name": "K. Tierney",       "position": "DF"},
        {"name": "C. McGregor",      "position": "MF"},
        {"name": "R. Gauld",         "position": "MF"},
        {"name": "L. Ferguson",      "position": "MF"},
        {"name": "B. Doak",          "position": "FW"},
        {"name": "D. Brooks",        "position": "FW"},
        {"name": "E. Ampadu",        "position": "MF"},
        {"name": "L. Trossard",      "position": "FW"},
        {"name": "T. Courtois",      "position": "GK"},
        {"name": "K. De Bruyne",     "position": "MF"},
        {"name": "R. Lukaku",        "position": "FW"},
        {"name": "L. Openda",        "position": "FW"},
        {"name": "J. Doku",          "position": "FW"},
        {"name": "Y. Carrasco",      "position": "MF"},
        {"name": "A. Witsel",        "position": "MF"},
        {"name": "A. Vermeeren",     "position": "MF"},
    ],
    "Belgium": [
        {"name": "T. Courtois",      "position": "GK"},
        {"name": "K. De Bruyne",     "position": "MF"},
        {"name": "R. Lukaku",        "position": "FW"},
        {"name": "L. Openda",        "position": "FW"},
        {"name": "L. Trossard",      "position": "FW"},
        {"name": "J. Doku",          "position": "FW"},
        {"name": "Y. Carrasco",      "position": "MF"},
        {"name": "A. Witsel",        "position": "MF"},
        {"name": "A. Vermeeren",     "position": "MF"},
        {"name": "T. Tielemans",     "position": "MF"},
        {"name": "J. Rodon",         "position": "DF"},
        {"name": "A. Robertson",     "position": "DF"},
        {"name": "J. McGinn",        "position": "MF"},
        {"name": "C. McGregor",      "position": "MF"},
        {"name": "K. Tierney",       "position": "DF"},
        {"name": "R. Gauld",         "position": "MF"},
        {"name": "S. McTominay",     "position": "MF"},
        {"name": "A. Witsel",        "position": "MF"},
        {"name": "A. Vermeeren",     "position": "MF"},
    ],
    "Norway": [
        {"name": "O. Nyland",        "position": "GK"},
        {"name": "E. Haaland",       "position": "FW"},
        {"name": "M. Odegaard",      "position": "MF"},
        {"name": "A. Sorloth",       "position": "FW"},
        {"name": "F. Aursnes",       "position": "MF"},
        {"name": "J. Ryerson",       "position": "DF"},
        {"name": "A. Pellegrino",    "position": "DF"},
        {"name": "J. Svensson",      "position": "DF"},
        {"name": "J. Brooks",        "position": "DF"},
        {"name": "O. Nyland",        "position": "GK"},
        {"name": "M. Flekken",       "position": "GK"},
        {"name": "B. Flekken",       "position": "GK"},
        {"name": "V. van Dijk",      "position": "DF"},
        {"name": "F. de Jong",       "position": "MF"},
        {"name": "X. Simons",        "position": "MF"},
        {"name": "D. Malen",         "position": "FW"},
        {"name": "M. de Ligt",       "position": "DF"},
        {"name": "J. Frimpong",      "position": "DF"},
        {"name": "C. Gakpo",         "position": "FW"},
    ],
    "Netherlands": [
        {"name": "B. Flekken",       "position": "GK"},
        {"name": "V. van Dijk",      "position": "DF"},
        {"name": "F. de Jong",       "position": "MF"},
        {"name": "X. Simons",        "position": "MF"},
        {"name": "D. Malen",         "position": "FW"},
        {"name": "M. de Ligt",       "position": "DF"},
        {"name": "J. Frimpong",      "position": "DF"},
        {"name": "C. Gakpo",         "position": "FW"},
        {"name": "K. Dumfries",      "position": "DF"},
        {"name": "T. Reijnders",     "position": "MF"},
        {"name": "W. Zaire-Emery",   "position": "MF"},
        {"name": "M. Maignan",       "position": "GK"},
        {"name": "K. Mbappe",        "position": "FW"},
        {"name": "A. Griezmann",     "position": "FW"},
        {"name": "A. Tchouameni",    "position": "MF"},
        {"name": "N. Kante",         "position": "MF"},
        {"name": "W. Saliba",        "position": "DF"},
        {"name": "K. Benzema",       "position": "FW"},
        {"name": "C. Nkunku",        "position": "FW"},
        {"name": "M. Depay",         "position": "FW"},
    ],
    "France": [
        {"name": "M. Maignan",       "position": "GK"},
        {"name": "K. Mbappe",        "position": "FW"},
        {"name": "A. Griezmann",     "position": "FW"},
        {"name": "A. Tchouameni",    "position": "MF"},
        {"name": "M. Camavinga",     "position": "MF"},
        {"name": "W. Saliba",        "position": "DF"},
        {"name": "N. Kante",         "position": "MF"},
        {"name": "K. Benzema",       "position": "FW"},
        {"name": "C. Nkunku",        "position": "FW"},
        {"name": "M. Depay",         "position": "FW"},
        {"name": "W. Zaire-Emery",   "position": "MF"},
        {"name": "J. Koundé",        "position": "DF"},
        {"name": "N. Kante",         "position": "MF"},
        {"name": "A. Coman",         "position": "FW"},
        {"name": "M. Maignan",       "position": "GK"},
    ],
    "Spain": [
        {"name": "U. Simon",         "position": "GK"},
        {"name": "Pedri",            "position": "MF"},
        {"name": "Rodri",            "position": "MF"},
        {"name": "L. Yamal",         "position": "FW"},
        {"name": "Morata",           "position": "FW"},
        {"name": "D. Olmo",          "position": "MF"},
        {"name": "Gavi",             "position": "MF"},
        {"name": "Carvajal",         "position": "DF"},
        {"name": "A. Grimaldo",      "position": "DF"},
        {"name": "Koke",             "position": "MF"},
        {"name": "Um Won Sang",      "position": "MF"},
        {"name": "Kim Young Gwon",   "position": "DF"},
        {"name": "F. Brown Forbes",  "position": "DF"},
        {"name": "D. Nakamura",      "position": "MF"},
        {"name": "K. Nakamura",      "position": "MF"},
        {"name": "A. Martinez",      "position": "DF"},
        {"name": "J. Koundé",        "position": "DF"},
        {"name": "J. Brown Forbes",  "position": "DF"},
        {"name": "N. Williams",      "position": "FW"},
    ],
    "Portugal": [
        {"name": "Rui Patricio",     "position": "GK"},
        {"name": "Cristiano Ronaldo","position": "FW"},
        {"name": "B. Fernandes",     "position": "MF"},
        {"name": "Rafael Leao",      "position": "FW"},
        {"name": "Joao Felix",       "position": "FW"},
        {"name": "Nuno Mendes",      "position": "DF"},
        {"name": "Ruben Dias",       "position": "DF"},
        {"name": "Bernardo Silva",   "position": "MF"},
        {"name": "Diogo Jota",       "position": "FW"},
        {"name": "Joao Cancelo",     "position": "DF"},
        {"name": "Joao Neves",       "position": "MF"},
        {"name": "Stefan Bajcetic",  "position": "MF"},
        {"name": "Diogo Dalot",      "position": "DF"},
        {"name": "V. Queirós",       "position": "GK"},
        {"name": "A. Sarloth",       "position": "FW"},
    ],
    "Italy": [
        {"name": "G. Donnarumma",    "position": "GK"},
        {"name": "F. Chiesa",        "position": "FW"},
        {"name": "N. Barella",       "position": "MF"},
        {"name": "C. Immobile",      "position": "FW"},
        {"name": "A. Bastoni",       "position": "DF"},
        {"name": "L. Pellegrini",    "position": "MF"},
        {"name": "G. Di Lorenzo",    "position": "DF"},
        {"name": "F. Dimarco",       "position": "DF"},
        {"name": "Jorginho",         "position": "MF"},
        {"name": "S. Pafundi",       "position": "FW"},
        {"name": "N. Pope",          "position": "GK"},
        {"name": "J. Bellingham",    "position": "MF"},
        {"name": "H. Kane",          "position": "FW"},
        {"name": "B. Saka",          "position": "FW"},
        {"name": "P. Foden",         "position": "MF"},
        {"name": "D. Rice",          "position": "MF"},
        {"name": "C. Palmer",        "position": "MF"},
        {"name": "R. Sterling",      "position": "FW"},
        {"name": "M. Rashford",      "position": "FW"},
        {"name": "T. Alexander-Arnold","position": "DF"},
    ],
    "England": [
        {"name": "J. Pickford",      "position": "GK"},
        {"name": "J. Bellingham",    "position": "MF"},
        {"name": "H. Kane",          "position": "FW"},
        {"name": "B. Saka",          "position": "FW"},
        {"name": "P. Foden",         "position": "MF"},
        {"name": "D. Rice",          "position": "MF"},
        {"name": "C. Palmer",        "position": "MF"},
        {"name": "R. Sterling",      "position": "FW"},
        {"name": "M. Rashford",      "position": "FW"},
        {"name": "N. Pope",          "position": "GK"},
        {"name": "T. Alexander-Arnold","position": "DF"},
        {"name": "K. Walker",        "position": "DF"},
        {"name": "J. Trippier",      "position": "DF"},
        {"name": "M. Guehi",         "position": "DF"},
        {"name": "O. Watkins",       "position": "FW"},
        {"name": "A. Gordon",        "position": "FW"},
    ],
    "Germany": [
        {"name": "M. ter Stegen",    "position": "GK"},
        {"name": "F. Wirtz",         "position": "MF"},
        {"name": "J. Kimmich",       "position": "MF"},
        {"name": "K. Havertz",       "position": "FW"},
        {"name": "J. Musiala",       "position": "MF"},
        {"name": "A. Rudiger",       "position": "DF"},
        {"name": "S. Gnabry",        "position": "FW"},
        {"name": "T. Alexander-Arnold","position": "DF"},
        {"name": "F. Balogun",       "position": "FW"},
        {"name": "I. Gundogan",      "position": "MF"},
        {"name": "J. Kimmich",       "position": "MF"},
        {"name": "L. Goretzka",      "position": "MF"},
        {"name": "N. Fullkrug",      "position": "FW"},
        {"name": "K. Adeyemi",       "position": "FW"},
        {"name": "D. Raum",          "position": "DF"},
    ],
    "Russia": [
        {"name": "M. Safonov",       "position": "GK"},
        {"name": "A. Golovin",       "position": "MF"},
        {"name": "F. Smolov",        "position": "FW"},
        {"name": "F. Chalov",        "position": "FW"},
        {"name": "A. Miranchuk",     "position": "MF"},
        {"name": "I. Diveev",        "position": "DF"},
        {"name": "V. Karpin",        "position": "MF"},
    ],

    # ── CONMEBOL ─────────────────────────────────────────────────────────────
    "Brazil": [
        {"name": "Alisson",          "position": "GK"},
        {"name": "Vini Jr.",         "position": "FW"},
        {"name": "Rodrygo",          "position": "FW"},
        {"name": "Casemiro",         "position": "MF"},
        {"name": "Thiago Silva",     "position": "DF"},
        {"name": "Gabriel Martinelli","position": "FW"},
        {"name": "Endrick",          "position": "FW"},
        {"name": "Neymar Jr.",       "position": "FW"},
        {"name": "Marquinhos",       "position": "DF"},
        {"name": "Gabriel Jesus",    "position": "FW"},
        {"name": "Matheus Martins",  "position": "FW"},
        {"name": "Danilo",           "position": "DF"},
        {"name": "Lucas Paqueta",    "position": "MF"},
        {"name": "Raphinha",         "position": "FW"},
        {"name": "Ederson",          "position": "GK"},
        {"name": "Bremer",           "position": "DF"},
        {"name": "Bruno Guimaraes",  "position": "MF"},
    ],
    "Ecuador": [
        {"name": "H. Galindez",      "position": "GK"},
        {"name": "M. Caicedo",       "position": "MF"},
        {"name": "A. Hincapie",      "position": "DF"},
        {"name": "G. Plata",         "position": "FW"},
        {"name": "J. Sornoza",       "position": "MF"},
        {"name": "E. Estupinan",     "position": "DF"},
        {"name": "D. Nunez",         "position": "FW"},
        {"name": "D. Gonzalez",      "position": "MF"},
        {"name": "A. Sanabria",      "position": "FW"},
        {"name": "A. Callens",       "position": "DF"},
        {"name": "E. Bolindos",      "position": "MF"},
        {"name": "P. Guerrero",      "position": "FW"},
        {"name": "A. Polo",          "position": "FW"},
        {"name": "A. Valera",        "position": "MF"},
        {"name": "J. Hutchinson",    "position": "MF"},
        {"name": "B. Cordova",       "position": "MF"},
        {"name": "D. Pizarro",       "position": "MF"},
    ],
    "Paraguay": [
        {"name": "A. Silva",         "position": "GK"},
        {"name": "M. Almeron",       "position": "MF"},
        {"name": "A. Sanabria",      "position": "FW"},
        {"name": "K. Paez",          "position": "MF"},
        {"name": "J. Enciso",        "position": "MF"},
        {"name": "D. Sanabria",      "position": "FW"},
        {"name": "O. Romero",        "position": "MF"},
        {"name": "J. Alonso",        "position": "MF"},
        {"name": "A. Espinoza",      "position": "DF"},
        {"name": "G. Villalba",      "position": "FW"},
        {"name": "J. Gamarra",       "position": "DF"},
        {"name": "R. Ortiz",         "position": "MF"},
        {"name": "F. Balbuena",      "position": "DF"},
        {"name": "R. Rojas",         "position": "MF"},
    ],
    "Mexico": [
        {"name": "G. Ochoa",         "position": "GK"},
        {"name": "H. Lozano",        "position": "FW"},
        {"name": "S. Gimenez",       "position": "FW"},
        {"name": "E. Alvarez",       "position": "MF"},
        {"name": "R. Jimenez",       "position": "FW"},
        {"name": "G. Ochoa",         "position": "GK"},
        {"name": "L. Chavez",        "position": "MF"},
        {"name": "O. Ocampo",        "position": "MF"},
        {"name": "A. Vega",          "position": "MF"},
        {"name": "I. Rodríguez",     "position": "GK"},
        {"name": "H. Herrera",       "position": "MF"},
        {"name": "C. Antuna",        "position": "FW"},
        {"name": "J. Macias",        "position": "FW"},
        {"name": "C. Salcedo",       "position": "DF"},
        {"name": "J. Araujo",        "position": "DF"},
        {"name": "N. Araujo",        "position": "DF"},
    ],
    "Panama": [
        {"name": "L. Mejia",         "position": "GK"},
        {"name": "A. Murillo",       "position": "DF"},
        {"name": "A. Carrasquilla",  "position": "MF"},
        {"name": "C. Waterman",      "position": "FW"},
        {"name": "A. Godoy",         "position": "FW"},
        {"name": "A. Andrade",       "position": "DF"},
        {"name": "J. Fajardo",       "position": "FW"},
        {"name": "E. Zorrilla",      "position": "MF"},
        {"name": "R. Torres",        "position": "DF"},
        {"name": "A. Mosquera",      "position": "DF"},
        {"name": "J. Davis",         "position": "MF"},
        {"name": "E. Tejada",        "position": "DF"},
        {"name": "E. Brown",         "position": "FW"},
    ],
    "Colombia": [
        {"name": "D. Vargas",        "position": "GK"},
        {"name": "L. Diaz",          "position": "FW"},
        {"name": "D. Munoz",         "position": "DF"},
        {"name": "J. Quintero",      "position": "MF"},
        {"name": "L. Muriel",        "position": "FW"},
        {"name": "R. Borre",         "position": "FW"},
        {"name": "S. Cordoba",       "position": "FW"},
        {"name": "D. Machis",        "position": "MF"},
        {"name": "J. Rodriguez",     "position": "MF"},
        {"name": "L. Sinisterra",    "position": "FW"},
        {"name": "K. Castaño",       "position": "MF"},
        {"name": "Y. Cuadrado",      "position": "MF"},
        {"name": "S. Arias",         "position": "DF"},
        {"name": "A. Moreno",        "position": "DF"},
        {"name": "R. Ospina",        "position": "GK"},
        {"name": "L. Montero",       "position": "FW"},
    ],
    "Chile": [
        {"name": "C. Bravo",         "position": "GK"},
        {"name": "A. Sanchez",       "position": "FW"},
        {"name": "G. Maripan",       "position": "DF"},
        {"name": "A. Vidal",         "position": "MF"},
        {"name": "B. Diaz",          "position": "DF"},
        {"name": "D. Nunez",         "position": "FW"},
        {"name": "D. Silva",         "position": "DF"},
        {"name": "D. Catano",        "position": "MF"},
        {"name": "C. Palacios",      "position": "MF"},
        {"name": "D. Pizarro",       "position": "MF"},
        {"name": "E. Bolindos",      "position": "MF"},
        {"name": "A. Sánchez",       "position": "FW"},
        {"name": "F. Orellana",      "position": "MF"},
        {"name": "N. Castillo",      "position": "FW"},
        {"name": "E. Vargas",        "position": "FW"},
    ],
    "Peru": [
        {"name": "P. Gallese",       "position": "GK"},
        {"name": "G. Lapadula",      "position": "FW"},
        {"name": "C. Cueva",         "position": "MF"},
        {"name": "A. Carrillo",      "position": "FW"},
        {"name": "Y. Yotun",         "position": "MF"},
        {"name": "A. Callens",       "position": "DF"},
        {"name": "L. Advincula",     "position": "DF"},
        {"name": "R. Tapia",         "position": "MF"},
        {"name": "P. Gallese",       "position": "GK"},
        {"name": "A. Polo",          "position": "FW"},
        {"name": "R. Ruidias",       "position": "MF"},
        {"name": "A. Vidal",         "position": "MF"},
        {"name": "S. Cueto",         "position": "MF"},
        {"name": "G. Quispe",        "position": "MF"},
    ],
    "Uruguay": [
        {"name": "S. Rochet",        "position": "GK"},
        {"name": "L. Suarez",        "position": "FW"},
        {"name": "D. Nunez",         "position": "FW"},
        {"name": "F. Valverde",      "position": "MF"},
        {"name": "J. Gimenez",       "position": "DF"},
        {"name": "R. Bentancur",     "position": "MF"},
        {"name": "S. Coates",        "position": "DF"},
        {"name": "M. Ugarte",        "position": "MF"},
        {"name": "R. Araujo",        "position": "DF"},
        {"name": "L. Torreria",      "position": "MF"},
        {"name": "F. Muslera",       "position": "GK"},
        {"name": "L. Suarez",        "position": "FW"},
        {"name": "F. Torres",        "position": "FW"},
        {"name": "M. Olivera",       "position": "DF"},
        {"name": "B. Tabarez",       "position": "MF"},
    ],
    "Venezuela": [
        {"name": "W. Farinez",       "position": "GK"},
        {"name": "Y. Rincon",        "position": "MF"},
        {"name": "S. Cordova",       "position": "FW"},
        {"name": "Y. Herrera",       "position": "MF"},
        {"name": "R. Romo",          "position": "MF"},
        {"name": "D. Machis",        "position": "FW"},
        {"name": "M. Enoumba",       "position": "DF"},
        {"name": "J. Villanueva",    "position": "FW"},
        {"name": "A. Murillo",       "position": "DF"},
        {"name": "C. Romero",        "position": "DF"},
        {"name": "J. Martinez",      "position": "FW"},
        {"name": "J. Abreu",         "position": "FW"},
        {"name": "C. Canelon",       "position": "MF"},
        {"name": "Y. Bello",         "position": "MF"},
    ],
    "Bolivia": [
        {"name": "C. Lampe",         "position": "GK"},
        {"name": "H. Vaca",          "position": "MF"},
        {"name": "D. Mancilla",      "position": "FW"},
        {"name": "J. Sanchez",       "position": "MF"},
        {"name": "D. Gonzalez",      "position": "MF"},
        {"name": "A. Bareiro",       "position": "FW"},
        {"name": "H. Herrera",       "position": "MF"},
        {"name": "M. Quinones",      "position": "MF"},
        {"name": "A. Quiroga",       "position": "MF"},
        {"name": "L. Sagredo",       "position": "MF"},
        {"name": "J. Moreno",        "position": "MF"},
        {"name": "E. Mojica",        "position": "DF"},
        {"name": "F. Alphanumeric",  "position": "DF"},
        {"name": "J. Jusino",        "position": "FW"},
        {"name": "M. Martins",       "position": "FW"},
    ],
    "Argentina": [
        {"name": "E. Martinez",      "position": "GK"},
        {"name": "L. Messi",         "position": "FW"},
        {"name": "J. Dybala",        "position": "FW"},
        {"name": "L. Martinez",      "position": "FW"},
        {"name": "C. Romero",        "position": "DF"},
        {"name": "A. Di Maria",      "position": "FW"},
        {"name": "E. Fernandez",     "position": "MF"},
        {"name": "R. De Paul",       "position": "MF"},
        {"name": "F. Valverde",      "position": "MF"},
        {"name": "M. Acuna",         "position": "DF"},
        {"name": "J. Alvarez",       "position": "FW"},
        {"name": "Mac Allister",     "position": "MF"},
        {"name": "L. Paredes",       "position": "MF"},
        {"name": "N. Molina",        "position": "DF"},
        {"name": "G. Lo Celso",      "position": "MF"},
        {"name": "T. Almada",        "position": "MF"},
        {"name": "L. Balerdi",       "position": "DF"},
    ],

    # ── CAF ──────────────────────────────────────────────────────────────────
    "South Africa": [
        {"name": "R. Williams",      "position": "GK"},
        {"name": "T. Zwane",         "position": "MF"},
        {"name": "P. Lakay",         "position": "FW"},
        {"name": "J. Barr",          "position": "DF"},
        {"name": "Foster",           "position": "GK"},
        {"name": "Mothiba",          "position": "FW"},
        {"name": "Links",            "position": "MF"},
        {"name": "Kodisang",         "position": "FW"},
        {"name": "Blom",             "position": "MF"},
        {"name": "Ngezana",          "position": "DF"},
        {"name": "Mailula",          "position": "FW"},
        {"name": "Shalulile",        "position": "FW"},
        {"name": "Mokoena",          "position": "MF"},
        {"name": "Keet",             "position": "GK"},
        {"name": "Dolly",            "position": "FW"},
        {"name": "Hlongwane",        "position": "FW"},
        {"name": "De Reuck",         "position": "DF"},
        {"name": "Lakay",            "position": "FW"},
    ],
    "Tunisia": [
        {"name": "A. Dahmen",        "position": "GK"},
        {"name": "Skhiri",           "position": "MF"},
        {"name": "Laidouni",         "position": "MF"},
        {"name": "Talbi",            "position": "DF"},
        {"name": "Khazri",           "position": "MF"},
        {"name": "Valery",           "position": "DF"},
        {"name": "Munir",            "position": "FW"},
        {"name": "Abdi",             "position": "MF"},
        {"name": "Bronn",            "position": "DF"},
        {"name": "Semenyo",          "position": "FW"},
        {"name": "Bguir",            "position": "FW"},
        {"name": "Layouni",          "position": "MF"},
        {"name": "Chaalali",         "position": "MF"},
        {"name": "Ben Slimane",      "position": "MF"},
        {"name": "Sliti",            "position": "FW"},
        {"name": "Kechrida",         "position": "DF"},
    ],
    "Ghana": [
        {"name": "L. Zigi",          "position": "GK"},
        {"name": "T. Partey",        "position": "MF"},
        {"name": "M. Kudus",         "position": "MF"},
        {"name": "E. Kissa",         "position": "FW"},
        {"name": "A. Ayew",          "position": "FW"},
        {"name": "Abdul Samed",      "position": "MF"},
        {"name": "Lamptey",          "position": "FW"},
        {"name": "Amartey",          "position": "DF"},
        {"name": "Djiku",            "position": "DF"},
        {"name": "Paintsil",         "position": "FW"},
        {"name": "N. Niakhat",       "position": "FW"},
        {"name": "K. Barbarouses",   "position": "FW"},
        {"name": "Mensah",           "position": "DF"},
        {"name": "Boateng",          "position": "DF"},
        {"name": "Schlupp",          "position": "MF"},
        {"name": "Semenyo",          "position": "FW"},
    ],
    "Senegal": [
        {"name": "E. Mendy",         "position": "GK"},
        {"name": "S. Mane",          "position": "FW"},
        {"name": "K. Koulibaly",     "position": "DF"},
        {"name": "N. Jackson",       "position": "FW"},
        {"name": "P. Sarr",          "position": "FW"},
        {"name": "I. Sarr",          "position": "MF"},
        {"name": "B. Dia",           "position": "FW"},
        {"name": "A. Diallo",        "position": "MF"},
        {"name": "Y. Sabaly",        "position": "DF"},
        {"name": "I. Gueye",         "position": "MF"},
        {"name": "S. Mane",          "position": "FW"},
        {"name": "L. Balde",         "position": "FW"},
        {"name": "P. Diallo",        "position": "MF"},
        {"name": "Niakhate",         "position": "DF"},
        {"name": "Ciss",             "position": "MF"},
    ],
    "Morocco": [
        {"name": "Y. Bono",          "position": "GK"},
        {"name": "A. Hakimi",        "position": "DF"},
        {"name": "H. Ziyech",        "position": "MF"},
        {"name": "Y. En-Nesyri",     "position": "FW"},
        {"name": "S. Amrabat",       "position": "MF"},
        {"name": "N. Mazraoui",      "position": "DF"},
        {"name": "Brahim",           "position": "FW"},
        {"name": "A. Ezzalzouli",    "position": "FW"},
        {"name": "A. Tagnaouti",     "position": "GK"},
        {"name": "Bounou",           "position": "GK"},
        {"name": "A. Ounahi",        "position": "MF"},
        {"name": "Y. Jabrane",       "position": "MF"},
        {"name": "S. Agerd",         "position": "DF"},
        {"name": "R. Attiyat Allah", "position": "DF"},
        {"name": "I. Benali",        "position": "MF"},
        {"name": "A. Harit",         "position": "MF"},
    ],
    "Egypt": [
        {"name": "M. El-Shenawy",    "position": "GK"},
        {"name": "M. Salah",         "position": "FW"},
        {"name": "O. Marmoush",      "position": "FW"},
        {"name": "A. Hassan",        "position": "MF"},
        {"name": "Trezeguet",        "position": "FW"},
        {"name": "A. Hegazi",        "position": "DF"},
        {"name": "Mosalah",          "position": "MF"},
        {"name": "Elneny",           "position": "MF"},
        {"name": "Shikabala",        "position": "FW"},
        {"name": "Mohamed",          "position": "MF"},
        {"name": "A. Diallo",        "position": "MF"},
        {"name": "El Shhat",         "position": "MF"},
        {"name": "S. Hamed",         "position": "DF"},
    ],
    "Ivory Coast": [
        {"name": "Y. Fofana",        "position": "GK"},
        {"name": "S. Haller",        "position": "FW"},
        {"name": "F. Kessie",        "position": "MF"},
        {"name": "W. Zaha",          "position": "FW"},
        {"name": "A. Sangare",       "position": "MF"},
        {"name": "M. Salah",         "position": "FW"},
        {"name": "I. Sangare",       "position": "MF"},
        {"name": "J. Fofana",        "position": "DF"},
        {"name": "G. Seri",          "position": "MF"},
        {"name": "N. Pepe",          "position": "FW"},
        {"name": "E. Kouame",        "position": "FW"},
        {"name": "O. Diallo",        "position": "DF"},
        {"name": "A. Gouiri",        "position": "FW"},
    ],
    "Cameroon": [
        {"name": "A. Onana",         "position": "GK"},
        {"name": "V. Aboubakar",     "position": "FW"},
        {"name": "Zambo Anguissa",   "position": "MF"},
        {"name": "B. Mbeumo",        "position": "FW"},
        {"name": "W. Boniface",      "position": "FW"},
        {"name": "M. Toko Ekamb",    "position": "FW"},
        {"name": "H. Moukoudi",      "position": "DF"},
        {"name": "Mfeka",            "position": "DF"},
        {"name": "J. Ngamaleu",      "position": "MF"},
        {"name": "G. Nkoudou",       "position": "FW"},
        {"name": "C. Bassogog",      "position": "FW"},
        {"name": "M. Wague",         "position": "DF"},
    ],
    "Nigeria": [
        {"name": "F. Uzoho",         "position": "GK"},
        {"name": "V. Osimhen",       "position": "FW"},
        {"name": "A. Lookman",       "position": "FW"},
        {"name": "A. Iwobi",         "position": "MF"},
        {"name": "T. Awoniyi",       "position": "FW"},
        {"name": "T. Aribo",         "position": "MF"},
        {"name": "W. Ndidi",         "position": "MF"},
        {"name": "M. Okoye",         "position": "GK"},
        {"name": "S. Chukwueze",     "position": "FW"},
        {"name": "J. Lookman",       "position": "FW"},
        {"name": "C. Chukwu",        "position": "DF"},
        {"name": "Z. Balogun",       "position": "FW"},
        {"name": "O. Aina",          "position": "DF"},
        {"name": "A. Bennacer",      "position": "MF"},
        {"name": "R. Troost-Ekong",  "position": "DF"},
    ],
    "Algeria": [
        {"name": "R. Mbolhi",        "position": "GK"},
        {"name": "R. Mahrez",        "position": "FW"},
        {"name": "I. Bennacer",      "position": "MF"},
        {"name": "S. Benrahma",      "position": "FW"},
        {"name": "Bensebaini",       "position": "DF"},
        {"name": "A. Ghezzal",       "position": "FW"},
        {"name": "K. Chaibi",        "position": "MF"},
        {"name": "A. Oukidja",       "position": "GK"},
        {"name": "A. Bentaleb",      "position": "MF"},
        {"name": "A. Belaili",       "position": "FW"},
        {"name": "Ait Nouri",        "position": "DF"},
        {"name": "M. Benali",        "position": "MF"},
        {"name": "H. Boudaoui",      "position": "MF"},
        {"name": "Z. Zerrouki",      "position": "MF"},
        {"name": "O. Bensebaini",    "position": "DF"},
    ],

    # ── CONCACAF ─────────────────────────────────────────────────────────────
    "Mexico": [
        {"name": "G. Ochoa",         "position": "GK"},
        {"name": "H. Lozano",        "position": "FW"},
        {"name": "S. Gimenez",       "position": "FW"},
        {"name": "E. Alvarez",       "position": "MF"},
        {"name": "R. Jimenez",       "position": "FW"},
        {"name": "L. Chavez",        "position": "MF"},
        {"name": "H. Herrera",       "position": "MF"},
        {"name": "C. Antuna",        "position": "FW"},
        {"name": "J. Macias",        "position": "FW"},
        {"name": "C. Salcedo",       "position": "DF"},
        {"name": "J. Araujo",        "position": "DF"},
        {"name": "E. Ochoa",         "position": "GK"},
        {"name": "O. Ocampo",        "position": "MF"},
        {"name": "A. Vega",          "position": "MF"},
        {"name": "A. Guardado",      "position": "MF"},
    ],
    "Panama": [
        {"name": "L. Mejia",         "position": "GK"},
        {"name": "A. Murillo",       "position": "DF"},
        {"name": "A. Carrasquilla",  "position": "MF"},
        {"name": "C. Waterman",      "position": "FW"},
        {"name": "A. Godoy",         "position": "FW"},
        {"name": "A. Andrade",       "position": "DF"},
        {"name": "J. Fajardo",       "position": "FW"},
        {"name": "E. Zorrilla",      "position": "MF"},
        {"name": "R. Torres",        "position": "DF"},
        {"name": "A. Mosquera",      "position": "DF"},
        {"name": "J. Davis",         "position": "MF"},
        {"name": "R. Brown",         "position": "DF"},
        {"name": "G. Torres",        "position": "MF"},
    ],
    "Costa Rica": [
        {"name": "K. Navas",         "position": "GK"},
        {"name": "J. Vargas",        "position": "MF"},
        {"name": "C. Gamboa",        "position": "DF"},
        {"name": "B. Ruiz",          "position": "FW"},
        {"name": "O. Duarte",        "position": "DF"},
        {"name": "J. Campbell",      "position": "FW"},
        {"name": "Y. Tejeda",        "position": "MF"},
        {"name": "C. Calvo",         "position": "MF"},
        {"name": "B. Brenes",        "position": "MF"},
        {"name": "R. Wyscott",       "position": "FW"},
        {"name": "D. Chacon",        "position": "DF"},
        {"name": "J. Cascante",      "position": "DF"},
        {"name": "A. Rudi",          "position": "FW"},
    ],
    "USA": [
        {"name": "M. Turner",        "position": "GK"},
        {"name": "C. Pulisic",       "position": "MF"},
        {"name": "G. Reyna",         "position": "MF"},
        {"name": "T. Adams",         "position": "MF"},
        {"name": "F. Balogun",       "position": "FW"},
        {"name": "C. Carter-Vickers","position": "DF"},
        {"name": "S. Dest",          "position": "DF"},
        {"name": "A. Robinson",      "position": "DF"},
        {"name": "M. Musah",         "position": "MF"},
        {"name": "Y. McKennie",      "position": "MF"},
        {"name": "W. McKennie",      "position": "MF"},
        {"name": "B. Aaronson",      "position": "MF"},
        {"name": "M. Miazga",        "position": "DF"},
        {"name": "Z. Reyna",         "position": "MF"},
        {"name": "R. Weah",          "position": "FW"},
    ],
    "Canada": [
        {"name": "M. Crepeau",       "position": "GK"},
        {"name": "A. Davies",        "position": "DF"},
        {"name": "J. David",         "position": "FW"},
        {"name": "T. Buchanan",      "position": "MF"},
        {"name": "S. Eustaquio",     "position": "MF"},
        {"name": "J. Pinnock",       "position": "DF"},
        {"name": "L. Millar",        "position": "FW"},
        {"name": "C. Larin",         "position": "FW"},
        {"name": "A. Johnston",      "position": "MF"},
        {"name": "I. Corbeanu",      "position": "MF"},
        {"name": "J. Waterman",      "position": "FW"},
        {"name": "R. Volcoff",       "position": "DF"},
        {"name": "D. Cornelius",     "position": "FW"},
        {"name": "M. Kaye",          "position": "MF"},
    ],
    "Jamaica": [
        {"name": "A. Blake",         "position": "GK"},
        {"name": "L. Bailey",        "position": "FW"},
        {"name": "K. Roofe",         "position": "FW"},
        {"name": "S. Nicholson",     "position": "FW"},
        {"name": "D. Gray",          "position": "MF"},
        {"name": "C. Larin",         "position": "FW"},
        {"name": "A. Johnston",      "position": "MF"},
        {"name": "D. Roofe",         "position": "FW"},
        {"name": "S. Lawrence",      "position": "DF"},
        {"name": "L. Williamson",    "position": "DF"},
        {"name": "N. Jackson",       "position": "FW"},
        {"name": "D. Latibeaudiere", "position": "DF"},
    ],

    # ── AFC ──────────────────────────────────────────────────────────────────
    "Korea": [
        {"name": "H. Son",           "position": "FW"},
        {"name": "Kim Min-jae",      "position": "DF"},
        {"name": "Lee Kang-in",      "position": "MF"},
        {"name": "Hwang Hee-chan",   "position": "FW"},
        {"name": "Hyeon Woo",        "position": "GK"},
        {"name": "Kim Min jae",      "position": "DF"},
        {"name": "Lee Jae Sung",     "position": "MF"},
        {"name": "Hong Hyeon Seok",  "position": "MF"},
        {"name": "Um Won Sang",      "position": "MF"},
        {"name": "Kim Young Gwon",   "position": "DF"},
        {"name": "Hwang In-beom",    "position": "MF"},
        {"name": "Na Sang-ho",       "position": "FW"},
        {"name": "Jung Woo-young",   "position": "MF"},
        {"name": "Kim Jin-su",       "position": "DF"},
        {"name": "Cho Gue-sung",     "position": "FW"},
        {"name": "Kwon Chang-hoon",  "position": "MF"},
    ],
    "Saudi Arabia": [
        {"name": "M. Al-Owais",      "position": "GK"},
        {"name": "S. Al-Dawsari",    "position": "FW"},
        {"name": "A. Al-Faraj",      "position": "MF"},
        {"name": "A. Al-Buraikan",   "position": "FW"},
        {"name": "A. Al-Mayoof",     "position": "GK"},
        {"name": "A. Sharahili",     "position": "DF"},
        {"name": "S. Abdulhamid",    "position": "DF"},
        {"name": "A. Al-Bulayhi",    "position": "DF"},
        {"name": "A. Al-Shahrani",   "position": "DF"},
        {"name": "A. Al-Ayeri",      "position": "FW"},
        {"name": "A. Al-Hatem",      "position": "MF"},
        {"name": "A. Khoukhi",       "position": "DF"},
        {"name": "H. Ahmed",         "position": "MF"},
        {"name": "M. Barsham",       "position": "GK"},
        {"name": "A. Al-Ghannam",    "position": "MF"},
        {"name": "F. Al-Muwallad",   "position": "FW"},
    ],
    "Japan": [
        {"name": "S. Gonda",         "position": "GK"},
        {"name": "T. Kubo",          "position": "MF"},
        {"name": "K. Mitoma",        "position": "FW"},
        {"name": "D. Kamada",        "position": "MF"},
        {"name": "T. Minamino",      "position": "MF"},
        {"name": "W. Endo",          "position": "MF"},
        {"name": "D. Nakamura",      "position": "MF"},
        {"name": "K. Sano",          "position": "MF"},
        {"name": "R. Doan",          "position": "MF"},
        {"name": "J. Ito",           "position": "FW"},
        {"name": "H. Ito",           "position": "FW"},
        {"name": "T. Tomiyasu",      "position": "DF"},
        {"name": "K. Nagatomo",      "position": "DF"},
        {"name": "Y. Ohshima",       "position": "MF"},
        {"name": "A. Iwata",         "position": "DF"},
        {"name": "M. Yoshida",       "position": "DF"},
    ],
    "Australia": [
        {"name": "M. Ryan",          "position": "GK"},
        {"name": "M. Leckie",        "position": "FW"},
        {"name": "A. Mooy",          "position": "MF"},
        {"name": "M. Duke",          "position": "FW"},
        {"name": "J. Irvine",        "position": "MF"},
        {"name": "M. Luongo",        "position": "MF"},
        {"name": "J. Maclaren",      "position": "FW"},
        {"name": "J. Brown Forbes",  "position": "DF"},
        {"name": "F. Brown Forbes",  "position": "DF"},
        {"name": "A. Elangue",       "position": "DF"},
        {"name": "A. Devlin",        "position": "DF"},
        {"name": "J. Maclarenm",     "position": "FW"},
        {"name": "G. Goodwin",       "position": "FW"},
        {"name": "T. Hamer",         "position": "MF"},
    ],
    "Iran": [
        {"name": "A. Beiranvand",    "position": "GK"},
        {"name": "S. Azmoun",        "position": "FW"},
        {"name": "M. Taremi",        "position": "FW"},
        {"name": "A. Jahanbakhsh",   "position": "FW"},
        {"name": "A. Montazeri",     "position": "GK"},
        {"name": "M. Hosseini",      "position": "DF"},
        {"name": "H. Saeidi",        "position": "MF"},
        {"name": "S. Ghoddos",       "position": "FW"},
        {"name": "K. Rezaeian",      "position": "MF"},
        {"name": "M. Karimi",        "position": "MF"},
        {"name": "S. Moharrami",     "position": "DF"},
        {"name": "A. Noorollahi",    "position": "MF"},
        {"name": "R. Pouraliganji", "position": "DF"},
    ],
    "Qatar": [
        {"name": "S. Al-Sheeb",      "position": "GK"},
        {"name": "A. Afif",          "position": "FW"},
        {"name": "H. Al-Haydos",     "position": "FW"},
        {"name": "M. Abu Fani",      "position": "MF"},
        {"name": "A. Al-Hatem",      "position": "MF"},
        {"name": "B. Khoukhi",       "position": "DF"},
        {"name": "M. Chacon",        "position": "DF"},
        {"name": "A. Asad",          "position": "DF"},
        {"name": "K. Boudiaf",       "position": "MF"},
        {"name": "L. Mendes",        "position": "MF"},
        {"name": "N. Khidir",        "position": "GK"},
        {"name": "P. Migael",        "position": "DF"},
        {"name": "Ismaeel",          "position": "FW"},
    ],

    # ── REPECHAJE ─────────────────────────────────────────────────────────────
    "New Zealand": [
        {"name": "A. Paulsen",       "position": "GK"},
        {"name": "C. Wood",          "position": "FW"},
        {"name": "K. Barbarouses",   "position": "FW"},
        {"name": "M. Boxall",        "position": "DF"},
        {"name": "L. Cacace",        "position": "DF"},
        {"name": "J. Bell",          "position": "DF"},
        {"name": "M. Stamenic",      "position": "MF"},
        {"name": "A. Rufer",         "position": "FW"},
        {"name": "T. Bindon",        "position": "MF"},
        {"name": "B. Old",           "position": "MF"},
        {"name": "O. Sail",          "position": "FW"},
        {"name": "J. Hamill",        "position": "MF"},
        {"name": "S. Payne",         "position": "DF"},
        {"name": "M. Nelsen",        "position": "DF"},
        {"name": "D. Thomas",        "position": "MF"},
    ],
}

INITIAL_FIFA_RANKING = {
    "France": 1840, "Spain": 1810, "England": 1780, "Germany": 1750,
    "Portugal": 1720, "Italy": 1690, "Netherlands": 1650, "Belgium": 1620,
    "Croatia": 1580, "Denmark": 1560, "Switzerland": 1530, "Norway": 1480,
    "Austria": 1450, "Sweden": 1420, "Poland": 1390, "Serbia": 1360,
    "Turkey": 1330, "Ukraine": 1310, "Czech Republic": 1280, "Greece": 1250,
    "Scotland": 1220, "Wales": 1200, "Iceland": 1150, "Russia": 1100,
    "Argentina": 1870, "Brazil": 1830, "Colombia": 1650, "Uruguay": 1620,
    "Chile": 1540, "Ecuador": 1510, "Paraguay": 1430, "Peru": 1380,
    "Bolivia": 1250, "Venezuela": 1230,
    "Senegal": 1630, "Morocco": 1600, "Tunisia": 1530, "Ghana": 1480,
    "Egypt": 1450, "Ivory Coast": 1440, "Nigeria": 1420, "Cameroon": 1390,
    "South Africa": 1330, "Algeria": 1350,
    "Mexico": 1550, "USA": 1530, "Canada": 1490, "Costa Rica": 1380,
    "Panama": 1360, "Jamaica": 1280,
    "Japan": 1560, "Korea": 1530, "Australia": 1470, "Saudi Arabia": 1420,
    "Iran": 1440, "Qatar": 1370,
    "New Zealand": 1100,
}

# ---------------------------------------------------------------------------
# FLAG MAP  -- England/Scotland/Wales usan \U escape para evitar el warning
# de GitHub sobre "bidirectional or hidden Unicode characters".
# En runtime Python los interpreta igual que los literales.
# ---------------------------------------------------------------------------
FLAG_MAP = {
    "France":        "\U0001F1EB\U0001F1F7",     # FR
    "Spain":         "\U0001F1EA\U0001F1F8",     # ES
    "England":       "\U0001F3F4\U000E0067\U000E0062\U000E0065\U000E006E\U000E0067\U000E007F",
    "Germany":       "\U0001F1E9\U0001F1EA",     # DE
    "Portugal":      "\U0001F1F5\U0001F1F9",     # PT
    "Italy":         "\U0001F1EE\U0001F1F9",     # IT
    "Netherlands":   "\U0001F1F3\U0001F1F1",     # NL
    "Belgium":       "\U0001F1E7\U0001F1EA",     # BE
    "Croatia":       "\U0001F1ED\U0001F1F7",     # HR
    "Denmark":       "\U0001F1E9\U0001F1F0",     # DK
    "Switzerland":   "\U0001F1E8\U0001F1ED",     # CH
    "Norway":        "\U0001F1F3\U0001F1F4",     # NO
    "Austria":       "\U0001F1E6\U0001F1F9",     # AT
    "Sweden":        "\U0001F1F8\U0001F1EA",     # SE
    "Poland":        "\U0001F1F5\U0001F1F1",     # PL
    "Serbia":        "\U0001F1F7\U0001F1F8",     # RS
    "Turkey":        "\U0001F1F9\U0001F1F7",     # TR
    "Ukraine":       "\U0001F1FA\U0001F1E6",     # UA
    "Czech Republic":"\U0001F1E8\U0001F1FF",     # CZ
    "Greece":        "\U0001F1EC\U0001F1F7",     # GR
    "Scotland":      "\U0001F3F4\U000E0067\U000E0062\U000E0073\U000E0063\U000E0074\U000E007F",
    "Wales":         "\U0001F3F4\U000E0067\U000E0062\U000E0077\U000E006C\U000E0073\U000E007F",
    "Iceland":       "\U0001F1EE\U0001F1F8",     # IS
    "Russia":        "\U0001F1F7\U0001F1FA",     # RU
    "Argentina":     "\U0001F1E6\U0001F1F7",     # AR
    "Brazil":        "\U0001F1E7\U0001F1F7",     # BR
    "Colombia":      "\U0001F1E8\U0001F1F4",     # CO
    "Uruguay":       "\U0001F1FA\U0001F1FE",     # UY
    "Chile":         "\U0001F1E8\U0001F1F1",     # CL
    "Ecuador":       "\U0001F1EA\U0001F1E8",     # EC
    "Paraguay":      "\U0001F1F5\U0001F1FE",     # PY
    "Peru":          "\U0001F1F5\U0001F1EA",     # PE
    "Bolivia":       "\U0001F1E7\U0001F1F4",     # BO
    "Venezuela":     "\U0001F1FB\U0001F1EA",     # VE
    "Senegal":       "\U0001F1F8\U0001F1F3",     # SN
    "Morocco":       "\U0001F1F2\U0001F1E6",     # MA
    "Tunisia":       "\U0001F1F9\U0001F1F3",     # TN
    "Ghana":         "\U0001F1EC\U0001F1ED",     # GH
    "Egypt":         "\U0001F1EA\U0001F1EC",     # EG
    "Ivory Coast":   "\U0001F1E8\U0001F1EE",     # CI
    "Nigeria":       "\U0001F1F3\U0001F1EC",     # NG
    "Cameroon":      "\U0001F1E8\U0001F1F2",     # CM
    "South Africa":  "\U0001F1FF\U0001F1E6",     # ZA
    "Algeria":       "\U0001F1E9\U0001F1FF",     # DZ
    "Mexico":        "\U0001F1F2\U0001F1FD",     # MX
    "USA":           "\U0001F1FA\U0001F1F8",     # US
    "Canada":        "\U0001F1E8\U0001F1E6",     # CA
    "Costa Rica":    "\U0001F1E8\U0001F1F7",     # CR
    "Panama":        "\U0001F1F5\U0001F1E6",     # PA
    "Jamaica":       "\U0001F1EF\U0001F1F2",     # JM
    "Japan":         "\U0001F1EF\U0001F1F5",     # JP
    "Korea":         "\U0001F1F0\U0001F1F7",     # KR
    "Australia":     "\U0001F1E6\U0001F1FA",     # AU
    "Saudi Arabia":  "\U0001F1F8\U0001F1E6",     # SA
    "Iran":          "\U0001F1EE\U0001F1F7",     # IR
    "Qatar":         "\U0001F1F6\U0001F1E6",     # QA
    "New Zealand":   "\U0001F1F3\U0001F1FF",     # NZ
}
