"""
data.py - Base de datos completa del simulador de Copa del Mundo
Equipos organizados por confederación con jugadores (extraídos de la imagen)
"""

# ============================================================
# EQUIPOS POR CONFEDERACIÓN
# ============================================================

# UEFA - Europa (24 equipos para Eurocopa)
UEFA_TEAMS = [
    "Switzerland", "Denmark", "Poland", "Austria", "Croatia", "Sweden",
    "Serbia", "Wales", "Scotland", "Belgium", "Colombia_UEFA",  # placeholder fix below
    "Ukraine", "Czech Republic", "Iceland", "Greece", "Turkey",
    "Norway", "Netherlands", "France", "Japan_UEFA",  # placeholder
    "Spain", "Portugal", "Italy", "England", "Germany"
]

# Corrección: UEFA real
UEFA_TEAMS = [
    "Switzerland", "Denmark", "Poland", "Austria", "Croatia",
    "Sweden", "Serbia", "Wales", "Scotland", "Belgium",
    "Ukraine", "Czech Republic", "Iceland", "Greece", "Turkey",
    "Norway", "Netherlands", "France", "Spain", "Portugal",
    "Italy", "England", "Germany", "Russia"
]

# CONMEBOL - Sudamérica (10 equipos)
CONMEBOL_TEAMS = [
    "Brazil", "Argentina", "Colombia", "Chile", "Peru",
    "Uruguay", "Venezuela", "Bolivia", "Paraguay", "Ecuador"
]

# CAF - África (10 equipos)
CAF_TEAMS = [
    "South Africa", "Morocco", "Tunisia", "Ghana", "Senegal",
    "Egypt", "Ivory Coast", "Cameroon", "Nigeria", "Algeria"
]

# CONCACAF - Concacaf (6 equipos para Copa Oro)
CONCACAF_TEAMS = [
    "Mexico", "Panama", "Costa Rica", "USA", "Canada", "Jamaica"
]

# AFC - Asia (6 equipos, Australia incluida)
AFC_TEAMS = [
    "Korea", "Saudi Arabia", "Japan", "Australia", "Iran", "Qatar"
]

# Repechaje independiente
PLAYOFF_TEAMS = ["New Zealand"]

# ============================================================
# JUGADORES POR SELECCIÓN (de la imagen)
# ============================================================

PLAYERS = {
    # ---- UEFA ----
    "Switzerland": [
        {"name": "Kobel", "sofifa_id": None, "position": "GK"},
        {"name": "K. Schmeichel", "sofifa_id": None, "position": "GK"},
        {"name": "G. Kobel", "sofifa_id": None, "position": "GK"},
        {"name": "G. Xhaka", "sofifa_id": None, "position": "MF"},
        {"name": "M. Akanji", "sofifa_id": None, "position": "DF"},
        {"name": "F. Schär", "sofifa_id": None, "position": "DF"},
        {"name": "R. Freuler", "sofifa_id": None, "position": "MF"},
        {"name": "D. Zakaria", "sofifa_id": None, "position": "MF"},
        {"name": "N. Elvedi", "sofifa_id": None, "position": "DF"},
        {"name": "R. Rodríguez", "sofifa_id": None, "position": "DF"},
        {"name": "B. Embolo", "sofifa_id": None, "position": "FW"},
        {"name": "N. Okafor", "sofifa_id": None, "position": "FW"},
    ],
    "Denmark": [
        {"name": "P. Schick", "sofifa_id": None, "position": "FW"},
        {"name": "A. Christensen", "sofifa_id": None, "position": "DF"},
        {"name": "M. Hjulmand", "sofifa_id": None, "position": "MF"},
        {"name": "C. Eriksen", "sofifa_id": None, "position": "MF"},
        {"name": "M. O'Riley", "sofifa_id": None, "position": "MF"},
        {"name": "J. Andersen", "sofifa_id": None, "position": "DF"},
        {"name": "A. Bah", "sofifa_id": None, "position": "DF"},
        {"name": "R. Højlund", "sofifa_id": None, "position": "FW"},
        {"name": "F. Kostić", "sofifa_id": None, "position": "MF"},
        {"name": "J. Rodon", "sofifa_id": None, "position": "DF"},
        {"name": "D. Tadić", "sofifa_id": None, "position": "FW"},
        {"name": "A. Mitrović", "sofifa_id": None, "position": "FW"},
    ],
    "Poland": [
        {"name": "S. Ingason", "sofifa_id": None, "position": "DF"},
        {"name": "Å. Guðmundsson", "sofifa_id": None, "position": "MF"},
        {"name": "H. Magnússon", "sofifa_id": None, "position": "DF"},
        {"name": "J. Guðmundsson", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hlože", "sofifa_id": None, "position": "FW"},
        {"name": "A. Sigurðsson", "sofifa_id": None, "position": "MF"},
        {"name": "J. Porsteinsson", "sofifa_id": None, "position": "DF"},
        {"name": "J. Pavlenka", "sofifa_id": None, "position": "GK"},
        {"name": "V. Černý", "sofifa_id": None, "position": "FW"},
        {"name": "M. Jurásek", "sofifa_id": None, "position": "DF"},
        {"name": "P. Zieliński", "sofifa_id": None, "position": "MF"},
        {"name": "P. Frankowski", "sofifa_id": None, "position": "DF"},
    ],
    "Austria": [
        {"name": "O. Vlachodimos", "sofifa_id": None, "position": "GK"},
        {"name": "K. Mavropanos", "sofifa_id": None, "position": "DF"},
        {"name": "V. Pavlidis", "sofifa_id": None, "position": "FW"},
        {"name": "K. Tsimikas", "sofifa_id": None, "position": "DF"},
        {"name": "A. Bakasetas", "sofifa_id": None, "position": "MF"},
        {"name": "T. Fountas", "sofifa_id": None, "position": "FW"},
        {"name": "M. Anderson", "sofifa_id": None, "position": "MF"},
        {"name": "H. Haraldsson", "sofifa_id": None, "position": "FW"},
        {"name": "G. Hlynnsson", "sofifa_id": None, "position": "MF"},
        {"name": "G. Koutsias", "sofifa_id": None, "position": "FW"},
        {"name": "D. Alaba", "sofifa_id": None, "position": "DF"},
        {"name": "A. Robertson", "sofifa_id": None, "position": "DF"},
    ],
    "Croatia": [
        {"name": "H. Çalhanoğlu", "sofifa_id": None, "position": "MF"},
        {"name": "O. Kökcü", "sofifa_id": None, "position": "MF"},
        {"name": "E. Ünal", "sofifa_id": None, "position": "FW"},
        {"name": "U. Çakır", "sofifa_id": None, "position": "GK"},
        {"name": "S. Özcan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Türküoğlu", "sofifa_id": None, "position": "FW"},
        {"name": "A. Bardakçı", "sofifa_id": None, "position": "DF"},
        {"name": "M. Demiral", "sofifa_id": None, "position": "DF"},
        {"name": "A. Güler", "sofifa_id": None, "position": "MF"},
        {"name": "K. De Bruyne", "sofifa_id": None, "position": "MF"},
        {"name": "L. Modrić", "sofifa_id": None, "position": "MF"},
        {"name": "L. Suárez", "sofifa_id": None, "position": "FW"},
    ],
    "Sweden": [
        {"name": "R. Olsen", "sofifa_id": None, "position": "GK"},
        {"name": "A. Isak", "sofifa_id": None, "position": "FW"},
        {"name": "D. Kulusevski", "sofifa_id": None, "position": "FW"},
        {"name": "V. Gyökeres", "sofifa_id": None, "position": "FW"},
        {"name": "E. Forsberg", "sofifa_id": None, "position": "MF"},
        {"name": "V. Lindelöf", "sofifa_id": None, "position": "DF"},
        {"name": "M. Svanberg", "sofifa_id": None, "position": "MF"},
        {"name": "J. Karlsson", "sofifa_id": None, "position": "MF"},
        {"name": "K. Olsson", "sofifa_id": None, "position": "MF"},
        {"name": "H. Larsson", "sofifa_id": None, "position": "FW"},
    ],
    "Serbia": [
        {"name": "J. Milinković-Savić", "sofifa_id": None, "position": "GK"},
        {"name": "S. Milinković-Savić", "sofifa_id": None, "position": "MF"},
        {"name": "V. Vlahović", "sofifa_id": None, "position": "FW"},
        {"name": "N. Gudelj", "sofifa_id": None, "position": "MF"},
        {"name": "N. Matić", "sofifa_id": None, "position": "MF"},
        {"name": "N. Milenković", "sofifa_id": None, "position": "DF"},
        {"name": "M. Milovanović", "sofifa_id": None, "position": "MF"},
    ],
    "Wales": [
        {"name": "W. Hennessey", "sofifa_id": None, "position": "GK"},
        {"name": "B. Johnson", "sofifa_id": None, "position": "DF"},
        {"name": "B. Davies", "sofifa_id": None, "position": "DF"},
        {"name": "J. McGinn", "sofifa_id": None, "position": "MF"},
        {"name": "E. Ampadu", "sofifa_id": None, "position": "MF"},
        {"name": "D. Brooks", "sofifa_id": None, "position": "MF"},
        {"name": "H. Wilson", "sofifa_id": None, "position": "MF"},
        {"name": "C. Roberts", "sofifa_id": None, "position": "FW"},
        {"name": "D. James", "sofifa_id": None, "position": "FW"},
        {"name": "L. Harris", "sofifa_id": None, "position": "FW"},
    ],
    "Scotland": [
        {"name": "A. Robertson", "sofifa_id": None, "position": "DF"},
        {"name": "K. Tierney", "sofifa_id": None, "position": "DF"},
        {"name": "L. Ferguson", "sofifa_id": None, "position": "MF"},
        {"name": "T. Cairney", "sofifa_id": None, "position": "MF"},
        {"name": "S. McTominay", "sofifa_id": None, "position": "MF"},
        {"name": "R. Gauld", "sofifa_id": None, "position": "MF"},
        {"name": "B. Doak", "sofifa_id": None, "position": "FW"},
    ],
    "Belgium": [
        {"name": "K. De Bruyne", "sofifa_id": None, "position": "MF"},
        {"name": "R. Lukaku", "sofifa_id": None, "position": "FW"},
        {"name": "L. Openda", "sofifa_id": None, "position": "FW"},
        {"name": "T. Courtois", "sofifa_id": None, "position": "GK"},
        {"name": "J. Trossard", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Tielemans", "sofifa_id": None, "position": "MF"},
        {"name": "A. Witsel", "sofifa_id": None, "position": "MF"},
        {"name": "A. Vermeeren", "sofifa_id": None, "position": "MF"},
    ],
    "Ukraine": [
        {"name": "V. Tsygankov", "sofifa_id": None, "position": "MF"},
        {"name": "O. Zinchenko", "sofifa_id": None, "position": "DF"},
        {"name": "R. Malinovskyi", "sofifa_id": None, "position": "MF"},
        {"name": "T. Stepanenko", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Rakitskyi", "sofifa_id": None, "position": "DF"},
        {"name": "M. Shaparenko", "sofifa_id": None, "position": "MF"},
        {"name": "A. Lunin", "sofifa_id": None, "position": "GK"},
        {"name": "V. Buyalskyi", "sofifa_id": None, "position": "MF"},
        {"name": "M. Matviienko", "sofifa_id": None, "position": "DF"},
        {"name": "M. Mudryk", "sofifa_id": None, "position": "FW"},
    ],
    "Czech Republic": [
        {"name": "P. Schick", "sofifa_id": None, "position": "FW"},
        {"name": "T. Soucek", "sofifa_id": None, "position": "MF"},
        {"name": "A. Barak", "sofifa_id": None, "position": "MF"},
        {"name": "V. Coufal", "sofifa_id": None, "position": "DF"},
        {"name": "A. Hlože", "sofifa_id": None, "position": "FW"},
        {"name": "L. Krejčí", "sofifa_id": None, "position": "DF"},
        {"name": "C. Eriksen", "sofifa_id": None, "position": "MF"},
    ],
    "Iceland": [
        {"name": "S. Ingason", "sofifa_id": None, "position": "DF"},
        {"name": "Å. Guðmundsson", "sofifa_id": None, "position": "MF"},
        {"name": "H. Magnússon", "sofifa_id": None, "position": "DF"},
        {"name": "J. Guðmundsson", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hlože", "sofifa_id": None, "position": "FW"},
        {"name": "A. Sigurðsson", "sofifa_id": None, "position": "MF"},
        {"name": "J. Porsteinsson", "sofifa_id": None, "position": "DF"},
        {"name": "R. Rúnarsson", "sofifa_id": None, "position": "GK"},
        {"name": "R. Hjulmand", "sofifa_id": None, "position": "MF"},
        {"name": "S. Kjær", "sofifa_id": None, "position": "DF"},
        {"name": "P. Højbjerg", "sofifa_id": None, "position": "MF"},
    ],
    "Greece": [
        {"name": "O. Vlachodimos", "sofifa_id": None, "position": "GK"},
        {"name": "K. Mavropanos", "sofifa_id": None, "position": "DF"},
        {"name": "V. Pavlidis", "sofifa_id": None, "position": "FW"},
        {"name": "K. Tsimikas", "sofifa_id": None, "position": "DF"},
        {"name": "A. Bakasetas", "sofifa_id": None, "position": "MF"},
        {"name": "T. Fountas", "sofifa_id": None, "position": "FW"},
        {"name": "G. Giakoumakis", "sofifa_id": None, "position": "FW"},
        {"name": "G. Koutsias", "sofifa_id": None, "position": "FW"},
        {"name": "D. Stanković", "sofifa_id": None, "position": "MF"},
        {"name": "K. Laimer", "sofifa_id": None, "position": "MF"},
        {"name": "A. Kramarić", "sofifa_id": None, "position": "FW"},
        {"name": "A. Robertson", "sofifa_id": None, "position": "DF"},
    ],
    "Turkey": [
        {"name": "H. Çalhanoğlu", "sofifa_id": None, "position": "MF"},
        {"name": "O. Kökcü", "sofifa_id": None, "position": "MF"},
        {"name": "E. Ünal", "sofifa_id": None, "position": "FW"},
        {"name": "U. Çakır", "sofifa_id": None, "position": "GK"},
        {"name": "S. Özcan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Türküoğlu", "sofifa_id": None, "position": "FW"},
        {"name": "A. Bardakçı", "sofifa_id": None, "position": "DF"},
        {"name": "M. Demiral", "sofifa_id": None, "position": "DF"},
        {"name": "A. Güler", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Carrasco", "sofifa_id": None, "position": "MF"},
        {"name": "A. Vermeeren", "sofifa_id": None, "position": "MF"},
    ],
    "Norway": [
        {"name": "Ø. Nyland", "sofifa_id": None, "position": "GK"},
        {"name": "E. Haaland", "sofifa_id": None, "position": "FW"},
        {"name": "M. Ødegaard", "sofifa_id": None, "position": "MF"},
        {"name": "F. Aursnes", "sofifa_id": None, "position": "MF"},
        {"name": "A. Sørloth", "sofifa_id": None, "position": "FW"},
        {"name": "S. Dest", "sofifa_id": None, "position": "DF"},
        {"name": "J. Ryerson", "sofifa_id": None, "position": "DF"},
        {"name": "J. Brooks", "sofifa_id": None, "position": "DF"},
        {"name": "V. van Dijk", "sofifa_id": None, "position": "DF"},
        {"name": "M. Flekken", "sofifa_id": None, "position": "GK"},
        {"name": "M. Maignan", "sofifa_id": None, "position": "GK"},
        {"name": "A. Griezmann", "sofifa_id": None, "position": "FW"},
    ],
    "Netherlands": [
        {"name": "V. van Dijk", "sofifa_id": None, "position": "DF"},
        {"name": "M. Flekken", "sofifa_id": None, "position": "GK"},
        {"name": "C. Pulisic", "sofifa_id": None, "position": "MF"},
        {"name": "G. Reyna", "sofifa_id": None, "position": "MF"},
        {"name": "W. McKennie", "sofifa_id": None, "position": "MF"},
        {"name": "F. de Jong", "sofifa_id": None, "position": "MF"},
        {"name": "F. Frimpong", "sofifa_id": None, "position": "DF"},
        {"name": "A. Griezmann", "sofifa_id": None, "position": "FW"},
        {"name": "A. Griezmann", "sofifa_id": None, "position": "FW"},
        {"name": "de Ligt", "sofifa_id": None, "position": "DF"},
        {"name": "D. Malen", "sofifa_id": None, "position": "FW"},
        {"name": "X. Simons", "sofifa_id": None, "position": "MF"},
    ],
    "France": [
        {"name": "M. Maignan", "sofifa_id": None, "position": "GK"},
        {"name": "A. Griezmann", "sofifa_id": None, "position": "FW"},
        {"name": "K. Mbappé", "sofifa_id": None, "position": "FW"},
        {"name": "A. Tchouaméni", "sofifa_id": None, "position": "MF"},
        {"name": "M. Camavinga", "sofifa_id": None, "position": "MF"},
        {"name": "W. Saliba", "sofifa_id": None, "position": "DF"},
        {"name": "T. Hernández", "sofifa_id": None, "position": "DF"},
        {"name": "O. Giroud", "sofifa_id": None, "position": "FW"},
        {"name": "M. Zaire-Emery", "sofifa_id": None, "position": "MF"},
    ],
    "Spain": [
        {"name": "Morata", "sofifa_id": None, "position": "FW"},
        {"name": "Pedri", "sofifa_id": None, "position": "MF"},
        {"name": "Rodri", "sofifa_id": None, "position": "MF"},
        {"name": "Thiago", "sofifa_id": None, "position": "MF"},
        {"name": "A. Grimaldo", "sofifa_id": None, "position": "DF"},
        {"name": "U. Simón", "sofifa_id": None, "position": "GK"},
        {"name": "G. Reyna", "sofifa_id": None, "position": "MF"},
        {"name": "C. Pulisic", "sofifa_id": None, "position": "MF"},
        {"name": "C. Ajer", "sofifa_id": None, "position": "DF"},
        {"name": "A. Robinson", "sofifa_id": None, "position": "DF"},
        {"name": "T. Adams", "sofifa_id": None, "position": "MF"},
        {"name": "J. Cascante", "sofifa_id": None, "position": "DF"},
        {"name": "K. Vargas", "sofifa_id": None, "position": "MF"},
        {"name": "D. Chacón", "sofifa_id": None, "position": "MF"},
        {"name": "A. Martínez", "sofifa_id": None, "position": "MF"},
        {"name": "N. Kanté", "sofifa_id": None, "position": "MF"},
        {"name": "C. Nkunku", "sofifa_id": None, "position": "FW"},
    ],
    "Portugal": [
        {"name": "Cristiano Ronaldo", "sofifa_id": None, "position": "FW"},
        {"name": "Rafael Leão", "sofifa_id": None, "position": "FW"},
        {"name": "Rui Patrício", "sofifa_id": None, "position": "GK"},
        {"name": "Rúben Dias", "sofifa_id": None, "position": "DF"},
        {"name": "Bernardo Silva", "sofifa_id": None, "position": "MF"},
        {"name": "João Cancelo", "sofifa_id": None, "position": "DF"},
        {"name": "Diogo Jota", "sofifa_id": None, "position": "FW"},
        {"name": "João Félix", "sofifa_id": None, "position": "FW"},
        {"name": "Nuno Mendes", "sofifa_id": None, "position": "DF"},
        {"name": "João Neves", "sofifa_id": None, "position": "MF"},
        {"name": "Diogo Dalot", "sofifa_id": None, "position": "DF"},
    ],
    "Italy": [
        {"name": "G. Donnarumma", "sofifa_id": None, "position": "GK"},
        {"name": "L. Pellegrini", "sofifa_id": None, "position": "MF"},
        {"name": "F. Dimarco", "sofifa_id": None, "position": "DF"},
        {"name": "N. Barella", "sofifa_id": None, "position": "MF"},
        {"name": "G. Di Lorenzo", "sofifa_id": None, "position": "DF"},
        {"name": "F. Chiesa", "sofifa_id": None, "position": "FW"},
        {"name": "A. Bastoni", "sofifa_id": None, "position": "DF"},
        {"name": "C. Immobile", "sofifa_id": None, "position": "FW"},
        {"name": "Jorginho", "sofifa_id": None, "position": "MF"},
        {"name": "S. Pafundi", "sofifa_id": None, "position": "FW"},
        {"name": "N. Pope", "sofifa_id": None, "position": "GK"},
        {"name": "P. Foden", "sofifa_id": None, "position": "MF"},
        {"name": "J. Bellingham", "sofifa_id": None, "position": "MF"},
        {"name": "B. Saka", "sofifa_id": None, "position": "FW"},
        {"name": "D. Rice", "sofifa_id": None, "position": "MF"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "F. Wirtz", "sofifa_id": None, "position": "MF"},
        {"name": "J. Kimmich", "sofifa_id": None, "position": "MF"},
    ],
    "England": [
        {"name": "N. Pope", "sofifa_id": None, "position": "GK"},
        {"name": "P. Foden", "sofifa_id": None, "position": "MF"},
        {"name": "J. Bellingham", "sofifa_id": None, "position": "MF"},
        {"name": "B. Saka", "sofifa_id": None, "position": "FW"},
        {"name": "D. Rice", "sofifa_id": None, "position": "MF"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "M. ter Stegen", "sofifa_id": None, "position": "GK"},
        {"name": "T. Müller", "sofifa_id": None, "position": "FW"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "J. Kimmich", "sofifa_id": None, "position": "MF"},
        {"name": "L. Goretzka", "sofifa_id": None, "position": "MF"},
    ],
    "Germany": [
        {"name": "M. ter Stegen", "sofifa_id": None, "position": "GK"},
        {"name": "F. Wirtz", "sofifa_id": None, "position": "MF"},
        {"name": "J. Kimmich", "sofifa_id": None, "position": "MF"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "T. Müller", "sofifa_id": None, "position": "FW"},
        {"name": "R. Gosens", "sofifa_id": None, "position": "DF"},
        {"name": "A. Rüdiger", "sofifa_id": None, "position": "DF"},
        {"name": "J. Gündoğan", "sofifa_id": None, "position": "MF"},
    ],
    "Russia": [
        {"name": "I. Akinfeev", "sofifa_id": None, "position": "GK"},
        {"name": "A. Golovin", "sofifa_id": None, "position": "MF"},
        {"name": "F. Smolov", "sofifa_id": None, "position": "FW"},
    ],

    # ---- CONMEBOL ----
    "Brazil": [
        {"name": "Neymar Jr", "sofifa_id": None, "position": "FW"},
        {"name": "Vini Jr.", "sofifa_id": None, "position": "FW"},
        {"name": "Casemiro", "sofifa_id": None, "position": "MF"},
        {"name": "Allison", "sofifa_id": None, "position": "GK"},
        {"name": "Thiago Silva", "sofifa_id": None, "position": "DF"},
        {"name": "Gabriel Jesús", "sofifa_id": None, "position": "FW"},
        {"name": "Gabriel Martinelli", "sofifa_id": None, "position": "FW"},
        {"name": "Rodrygo", "sofifa_id": None, "position": "FW"},
        {"name": "Matheus Martins", "sofifa_id": None, "position": "FW"},
        {"name": "D. Muñoz", "sofifa_id": None, "position": "DF"},
        {"name": "L. Muriel", "sofifa_id": None, "position": "FW"},
        {"name": "D. Mojica", "sofifa_id": None, "position": "DF"},
        {"name": "J. Quintero", "sofifa_id": None, "position": "MF"},
        {"name": "D. Silva", "sofifa_id": None, "position": "MF"},
        {"name": "D. Cataño", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Asprilla", "sofifa_id": None, "position": "FW"},
    ],
    "Argentina": [
        {"name": "L. Messi", "sofifa_id": None, "position": "FW"},
        {"name": "L. Martínez", "sofifa_id": None, "position": "FW"},
        {"name": "J. Dybala", "sofifa_id": None, "position": "FW"},
        {"name": "J. Jiménez", "sofifa_id": None, "position": "MF"},
        {"name": "Á. Álvarez", "sofifa_id": None, "position": "MF"},
        {"name": "R. Araujo", "sofifa_id": None, "position": "DF"},
        {"name": "Á. Di María", "sofifa_id": None, "position": "FW"},
        {"name": "S. Coates", "sofifa_id": None, "position": "DF"},
        {"name": "G. Maripán", "sofifa_id": None, "position": "DF"},
        {"name": "A. Vidal", "sofifa_id": None, "position": "MF"},
        {"name": "R. Ruidiaz", "sofifa_id": None, "position": "FW"},
        {"name": "A. Callens", "sofifa_id": None, "position": "DF"},
    ],
    "Colombia": [
        {"name": "D. Muñoz", "sofifa_id": None, "position": "DF"},
        {"name": "L. Muriel", "sofifa_id": None, "position": "FW"},
        {"name": "D. Mojica", "sofifa_id": None, "position": "DF"},
        {"name": "J. Quintero", "sofifa_id": None, "position": "MF"},
        {"name": "D. Silva", "sofifa_id": None, "position": "MF"},
        {"name": "D. Cataño", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Asprilla", "sofifa_id": None, "position": "FW"},
        {"name": "C. Palacios", "sofifa_id": None, "position": "MF"},
        {"name": "A. Polo", "sofifa_id": None, "position": "FW"},
        {"name": "D. Pizarro", "sofifa_id": None, "position": "MF"},
    ],
    "Chile": [
        {"name": "S. Coates", "sofifa_id": None, "position": "DF"},
        {"name": "G. Maripán", "sofifa_id": None, "position": "DF"},
        {"name": "A. Vidal", "sofifa_id": None, "position": "MF"},
        {"name": "R. Ruidiaz", "sofifa_id": None, "position": "FW"},
        {"name": "A. Callens", "sofifa_id": None, "position": "DF"},
        {"name": "C. Bravo", "sofifa_id": None, "position": "GK"},
        {"name": "A. Sánchez", "sofifa_id": None, "position": "FW"},
    ],
    "Peru": [
        {"name": "P. Gallese", "sofifa_id": None, "position": "GK"},
        {"name": "A. Lapadula", "sofifa_id": None, "position": "FW"},
        {"name": "A. Polo", "sofifa_id": None, "position": "FW"},
        {"name": "E. Palacios", "sofifa_id": None, "position": "MF"},
        {"name": "G. Guerrero", "sofifa_id": None, "position": "FW"},
        {"name": "A. Valera", "sofifa_id": None, "position": "MF"},
    ],
    "Uruguay": [
        {"name": "L. Suárez", "sofifa_id": None, "position": "FW"},
        {"name": "E. Cavani", "sofifa_id": None, "position": "FW"},
        {"name": "F. Valverde", "sofifa_id": None, "position": "MF"},
        {"name": "R. Bentancur", "sofifa_id": None, "position": "MF"},
        {"name": "L. Torreira", "sofifa_id": None, "position": "MF"},
        {"name": "D. Godín", "sofifa_id": None, "position": "DF"},
        {"name": "L. Giménez", "sofifa_id": None, "position": "MF"},
        {"name": "J. Giménez", "sofifa_id": None, "position": "DF"},
        {"name": "J. Trossard", "sofifa_id": None, "position": "MF"},
        {"name": "L. Trossard", "sofifa_id": None, "position": "MF"},
        {"name": "J. Quintero", "sofifa_id": None, "position": "MF"},
        {"name": "L. Sinisterra", "sofifa_id": None, "position": "FW"},
        {"name": "Y. Asprilla", "sofifa_id": None, "position": "FW"},
    ],
    "Venezuela": [
        {"name": "Y. Herrera", "sofifa_id": None, "position": "MF"},
        {"name": "R. Romo", "sofifa_id": None, "position": "DF"},
        {"name": "E. Martínez", "sofifa_id": None, "position": "GK"},
        {"name": "F. Muslera", "sofifa_id": None, "position": "GK"},
        {"name": "C. Romero", "sofifa_id": None, "position": "DF"},
        {"name": "C. Cáceres", "sofifa_id": None, "position": "DF"},
        {"name": "L. Cádiz", "sofifa_id": None, "position": "MF"},
        {"name": "L. González", "sofifa_id": None, "position": "MF"},
        {"name": "A. Quiroga", "sofifa_id": None, "position": "MF"},
        {"name": "J. Villanueva", "sofifa_id": None, "position": "MF"},
        {"name": "A. Sánchez", "sofifa_id": None, "position": "FW"},
        {"name": "R. Tapia", "sofifa_id": None, "position": "MF"},
        {"name": "L. Bailey", "sofifa_id": None, "position": "FW"},
        {"name": "A. Davies", "sofifa_id": None, "position": "DF"},
        {"name": "A. Johnston", "sofifa_id": None, "position": "MF"},
        {"name": "A. Bell", "sofifa_id": None, "position": "DF"},
        {"name": "A. Hutchinson", "sofifa_id": None, "position": "DF"},
    ],
    "Bolivia": [
        {"name": "S. Galindo", "sofifa_id": None, "position": "MF"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "M. Enuomba", "sofifa_id": None, "position": "FW"},
        {"name": "H. Vaca", "sofifa_id": None, "position": "MF"},
        {"name": "J. Musiala", "sofifa_id": None, "position": "MF"},
        {"name": "L. Sané", "sofifa_id": None, "position": "FW"},
        {"name": "D. Mancilla", "sofifa_id": None, "position": "FW"},
    ],
    "Paraguay": [
        {"name": "M. Caicedo", "sofifa_id": None, "position": "MF"},
        {"name": "M. Almirón", "sofifa_id": None, "position": "MF"},
        {"name": "G. Ochoa", "sofifa_id": None, "position": "GK"},
        {"name": "A. Murillo", "sofifa_id": None, "position": "DF"},
        {"name": "A. Godoy", "sofifa_id": None, "position": "MF"},
        {"name": "A. Sanabria", "sofifa_id": None, "position": "FW"},
        {"name": "A. Alderete", "sofifa_id": None, "position": "DF"},
        {"name": "A. González", "sofifa_id": None, "position": "MF"},
        {"name": "A. Sánchez", "sofifa_id": None, "position": "FW"},
        {"name": "E. Sánchez", "sofifa_id": None, "position": "FW"},
        {"name": "A. Bareiro", "sofifa_id": None, "position": "FW"},
        {"name": "A. Cubas", "sofifa_id": None, "position": "MF"},
        {"name": "A. Espínola", "sofifa_id": None, "position": "MF"},
        {"name": "C. Ramos", "sofifa_id": None, "position": "FW"},
        {"name": "J. Enciso", "sofifa_id": None, "position": "MF"},
        {"name": "K. Páez", "sofifa_id": None, "position": "MF"},
        {"name": "M. Ramírez", "sofifa_id": None, "position": "MF"},
        {"name": "C. Maripán", "sofifa_id": None, "position": "DF"},
        {"name": "B. Cordova", "sofifa_id": None, "position": "MF"},
        {"name": "K. Roofe", "sofifa_id": None, "position": "FW"},
        {"name": "S. Nicholson", "sofifa_id": None, "position": "FW"},
        {"name": "T. Buchanan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Polo", "sofifa_id": None, "position": "FW"},
    ],
    "Ecuador": [
        {"name": "M. Caicedo", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hincapié", "sofifa_id": None, "position": "DF"},
        {"name": "A. Álvarez", "sofifa_id": None, "position": "FW"},
        {"name": "Á. Alvarado", "sofifa_id": None, "position": "MF"},
        {"name": "D. González", "sofifa_id": None, "position": "MF"},
        {"name": "J. Sornoza", "sofifa_id": None, "position": "MF"},
        {"name": "D. Espínola", "sofifa_id": None, "position": "MF"},
        {"name": "J. Ramírez", "sofifa_id": None, "position": "MF"},
        {"name": "J. Espínola", "sofifa_id": None, "position": "MF"},
        {"name": "C. Montes", "sofifa_id": None, "position": "MF"},
        {"name": "D. Palacios", "sofifa_id": None, "position": "MF"},
        {"name": "L. Chávez", "sofifa_id": None, "position": "MF"},
        {"name": "J. Rodríguez", "sofifa_id": None, "position": "MF"},
        {"name": "E. Álvarez", "sofifa_id": None, "position": "MF"},
        {"name": "S. Giménez", "sofifa_id": None, "position": "FW"},
        {"name": "A. Carrasquilla", "sofifa_id": None, "position": "MF"},
        {"name": "Á. Angulo", "sofifa_id": None, "position": "MF"},
        {"name": "L. Sané", "sofifa_id": None, "position": "FW"},
        {"name": "A. Rüdiger", "sofifa_id": None, "position": "DF"},
        {"name": "J. Chura", "sofifa_id": None, "position": "MF"},
        {"name": "J. Sagredo", "sofifa_id": None, "position": "DF"},
        {"name": "J. Brandt", "sofifa_id": None, "position": "MF"},
        {"name": "Z. Kalmár", "sofifa_id": None, "position": "MF"},
        {"name": "D. Sallói", "sofifa_id": None, "position": "FW"},
        {"name": "K. Lisztes", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hutchinson", "sofifa_id": None, "position": "DF"},
        {"name": "A. Valera", "sofifa_id": None, "position": "MF"},
    ],

    # ---- CAF ----
    "South Africa": [
        {"name": "J. Barr", "sofifa_id": None, "position": "GK"},
        {"name": "M. Ryan", "sofifa_id": None, "position": "GK"},
        {"name": "C. Goodwin", "sofifa_id": None, "position": "DF"},
        {"name": "J. Irvine", "sofifa_id": None, "position": "MF"},
        {"name": "M. Leckie", "sofifa_id": None, "position": "FW"},
        {"name": "R. McGree", "sofifa_id": None, "position": "MF"},
        {"name": "A. Grant", "sofifa_id": None, "position": "MF"},
        {"name": "J. Maclaren", "sofifa_id": None, "position": "FW"},
        {"name": "A. Lookman", "sofifa_id": None, "position": "FW"},
        {"name": "J. Matip", "sofifa_id": None, "position": "DF"},
        {"name": "V. Osimhen", "sofifa_id": None, "position": "FW"},
        {"name": "M. Solomon", "sofifa_id": None, "position": "MF"},
        {"name": "N. Didi", "sofifa_id": None, "position": "MF"},
        {"name": "T. Moffi", "sofifa_id": None, "position": "FW"},
        {"name": "G. Nkoudou", "sofifa_id": None, "position": "FW"},
        {"name": "O. Kossounou", "sofifa_id": None, "position": "DF"},
        {"name": "S. Nwankwo", "sofifa_id": None, "position": "FW"},
        {"name": "C. Baleba", "sofifa_id": None, "position": "MF"},
    ],
    "Morocco": [
        {"name": "Dahmen", "sofifa_id": None, "position": "GK"},
        {"name": "Khazri", "sofifa_id": None, "position": "MF"},
        {"name": "Laidouni", "sofifa_id": None, "position": "MF"},
        {"name": "Talbi", "sofifa_id": None, "position": "DF"},
        {"name": "Mazraoui", "sofifa_id": None, "position": "DF"},
        {"name": "N. Mazraoui", "sofifa_id": None, "position": "DF"},
        {"name": "A. Hakimi", "sofifa_id": None, "position": "DF"},
        {"name": "M. Salah", "sofifa_id": None, "position": "FW"},
        {"name": "Y. En-Nesyri", "sofifa_id": None, "position": "FW"},
        {"name": "Brahim", "sofifa_id": None, "position": "MF"},
        {"name": "A. Ezzalzouli", "sofifa_id": None, "position": "FW"},
        {"name": "A. Onana", "sofifa_id": None, "position": "GK"},
        {"name": "Zambo Anguis", "sofifa_id": None, "position": "MF"},
        {"name": "A. Aboubakar", "sofifa_id": None, "position": "FW"},
        {"name": "V. Aboubakar", "sofifa_id": None, "position": "FW"},
        {"name": "W. Bboniface", "sofifa_id": None, "position": "FW"},
        {"name": "Mbeumo", "sofifa_id": None, "position": "FW"},
        {"name": "W. Zaha", "sofifa_id": None, "position": "FW"},
        {"name": "A. Diallo", "sofifa_id": None, "position": "DF"},
        {"name": "A. Bounami", "sofifa_id": None, "position": "MF"},
    ],
    "Tunisia": [
        {"name": "Skhiri", "sofifa_id": None, "position": "MF"},
        {"name": "Aidoo", "sofifa_id": None, "position": "DF"},
        {"name": "Kudus", "sofifa_id": None, "position": "MF"},
        {"name": "Lamptey", "sofifa_id": None, "position": "DF"},
        {"name": "Bguir", "sofifa_id": None, "position": "MF"},
        {"name": "Ngezana", "sofifa_id": None, "position": "DF"},
        {"name": "Abdi", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hassan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Ezzalzouli", "sofifa_id": None, "position": "FW"},
        {"name": "A. Onana", "sofifa_id": None, "position": "GK"},
        {"name": "Moffi", "sofifa_id": None, "position": "FW"},
        {"name": "Awoniyi", "sofifa_id": None, "position": "FW"},
        {"name": "H. Moukoudi", "sofifa_id": None, "position": "DF"},
        {"name": "Toko Ekambi", "sofifa_id": None, "position": "FW"},
        {"name": "O. Kouamé", "sofifa_id": None, "position": "FW"},
        {"name": "F. Chaibi", "sofifa_id": None, "position": "MF"},
        {"name": "C. Baleba", "sofifa_id": None, "position": "MF"},
    ],
    "Ghana": [
        {"name": "T. Partey", "sofifa_id": None, "position": "MF"},
        {"name": "L. Zigi", "sofifa_id": None, "position": "GK"},
        {"name": "A. Paulsen", "sofifa_id": None, "position": "DF"},
        {"name": "A. Rufer", "sofifa_id": None, "position": "DF"},
        {"name": "T. Bindon", "sofifa_id": None, "position": "MF"},
        {"name": "M. Boxall", "sofifa_id": None, "position": "DF"},
        {"name": "Djiku", "sofifa_id": None, "position": "DF"},
        {"name": "Abdul Samed", "sofifa_id": None, "position": "MF"},
        {"name": "Valery", "sofifa_id": None, "position": "FW"},
        {"name": "Paintsil", "sofifa_id": None, "position": "FW"},
        {"name": "K. Barbarouses", "sofifa_id": None, "position": "FW"},
        {"name": "B. Old", "sofifa_id": None, "position": "MF"},
    ],
    "Senegal": [
        {"name": "S. Mané", "sofifa_id": None, "position": "FW"},
        {"name": "K. Koulibaly", "sofifa_id": None, "position": "DF"},
        {"name": "B. Dia", "sofifa_id": None, "position": "FW"},
        {"name": "P. Sarr", "sofifa_id": None, "position": "FW"},
        {"name": "N. Jackson", "sofifa_id": None, "position": "FW"},
        {"name": "I. Gueye", "sofifa_id": None, "position": "MF"},
        {"name": "Y. Sabaly", "sofifa_id": None, "position": "DF"},
        {"name": "I. Sarr", "sofifa_id": None, "position": "FW"},
        {"name": "I. Bennacer", "sofifa_id": None, "position": "MF"},
        {"name": "N. Bentaleb", "sofifa_id": None, "position": "MF"},
        {"name": "A. Gouiri", "sofifa_id": None, "position": "FW"},
        {"name": "R. Bensebaini", "sofifa_id": None, "position": "DF"},
        {"name": "S. Benrahma", "sofifa_id": None, "position": "FW"},
        {"name": "A. Diallo", "sofifa_id": None, "position": "DF"},
        {"name": "A. Bounami", "sofifa_id": None, "position": "MF"},
    ],
    "Egypt": [
        {"name": "M. Salah", "sofifa_id": None, "position": "FW"},
        {"name": "A. Hassan", "sofifa_id": None, "position": "MF"},
        {"name": "Omar Marmoush", "sofifa_id": None, "position": "FW"},
        {"name": "Mohamed Elneny", "sofifa_id": None, "position": "MF"},
        {"name": "Ahmed Hegazi", "sofifa_id": None, "position": "DF"},
        {"name": "Trezeguet", "sofifa_id": None, "position": "FW"},
        {"name": "Mohamed Morsy", "sofifa_id": None, "position": "MF"},
    ],
    "Ivory Coast": [
        {"name": "F. Kessié", "sofifa_id": None, "position": "MF"},
        {"name": "S. Fofana", "sofifa_id": None, "position": "MF"},
        {"name": "A. Onana", "sofifa_id": None, "position": "GK"},
        {"name": "N. Pépe", "sofifa_id": None, "position": "FW"},
        {"name": "Zambo Anguis", "sofifa_id": None, "position": "MF"},
        {"name": "V. Aboubakar", "sofifa_id": None, "position": "FW"},
        {"name": "W. Bonfie", "sofifa_id": None, "position": "FW"},
        {"name": "Mbeumo", "sofifa_id": None, "position": "FW"},
        {"name": "W. Zaha", "sofifa_id": None, "position": "FW"},
    ],
    "Cameroon": [
        {"name": "A. Onana", "sofifa_id": None, "position": "GK"},
        {"name": "Zambo Anguissa", "sofifa_id": None, "position": "MF"},
        {"name": "V. Aboubakar", "sofifa_id": None, "position": "FW"},
        {"name": "W. Bonfie", "sofifa_id": None, "position": "FW"},
        {"name": "Mbeumo", "sofifa_id": None, "position": "FW"},
        {"name": "G. Nkoudou", "sofifa_id": None, "position": "FW"},
        {"name": "H. Moukoudi", "sofifa_id": None, "position": "DF"},
        {"name": "Toko Ekambi", "sofifa_id": None, "position": "FW"},
    ],
    "Nigeria": [
        {"name": "A. Lookman", "sofifa_id": None, "position": "FW"},
        {"name": "V. Osimhen", "sofifa_id": None, "position": "FW"},
        {"name": "J. Matip", "sofifa_id": None, "position": "DF"},
        {"name": "S. Nwankwo", "sofifa_id": None, "position": "FW"},
        {"name": "T. Moffi", "sofifa_id": None, "position": "FW"},
        {"name": "G. Nkoudou", "sofifa_id": None, "position": "FW"},
        {"name": "Zambo Anguissa", "sofifa_id": None, "position": "MF"},
        {"name": "Awoniyi", "sofifa_id": None, "position": "FW"},
    ],
    "Algeria": [
        {"name": "R. Mahrez", "sofifa_id": None, "position": "FW"},
        {"name": "I. Bennacer", "sofifa_id": None, "position": "MF"},
        {"name": "N. Bentaleb", "sofifa_id": None, "position": "MF"},
        {"name": "R. Bensebaini", "sofifa_id": None, "position": "DF"},
        {"name": "S. Benrahma", "sofifa_id": None, "position": "FW"},
        {"name": "A. Gouiri", "sofifa_id": None, "position": "FW"},
        {"name": "O. Kossounou", "sofifa_id": None, "position": "DF"},
    ],

    # ---- CONCACAF ----
    "Mexico": [
        {"name": "G. Ochoa", "sofifa_id": None, "position": "GK"},
        {"name": "H. Lozano", "sofifa_id": None, "position": "FW"},
        {"name": "Kaku", "sofifa_id": None, "position": "MF"},
        {"name": "A. Hincapié", "sofifa_id": None, "position": "DF"},
        {"name": "S. Giménez", "sofifa_id": None, "position": "FW"},
        {"name": "E. Álvarez", "sofifa_id": None, "position": "MF"},
        {"name": "J. Rodríguez", "sofifa_id": None, "position": "MF"},
        {"name": "A. Andrade", "sofifa_id": None, "position": "MF"},
        {"name": "J. Jiménez", "sofifa_id": None, "position": "MF"},
        {"name": "C. Waterman", "sofifa_id": None, "position": "FW"},
        {"name": "L. Chávez", "sofifa_id": None, "position": "MF"},
        {"name": "L. Mejía", "sofifa_id": None, "position": "MF"},
        {"name": "J. Musala", "sofifa_id": None, "position": "MF"},
        {"name": "M. Rashford", "sofifa_id": None, "position": "FW"},
        {"name": "K. Havertz", "sofifa_id": None, "position": "FW"},
        {"name": "J. Gündoğan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Jusino", "sofifa_id": None, "position": "DF"},
        {"name": "S. Gnabry", "sofifa_id": None, "position": "FW"},
        {"name": "H. Kane", "sofifa_id": None, "position": "FW"},
        {"name": "C. Palmer", "sofifa_id": None, "position": "MF"},
        {"name": "J. Osorio", "sofifa_id": None, "position": "MF"},
        {"name": "Z. Kalmár", "sofifa_id": None, "position": "MF"},
        {"name": "D. Sallói", "sofifa_id": None, "position": "FW"},
        {"name": "K. Lisztes", "sofifa_id": None, "position": "MF"},
        {"name": "K. Barbarouses", "sofifa_id": None, "position": "FW"},
        {"name": "A. Saliba", "sofifa_id": None, "position": "DF"},
    ],
    "Panama": [
        {"name": "A. Murillo", "sofifa_id": None, "position": "DF"},
        {"name": "A. Godoy", "sofifa_id": None, "position": "MF"},
        {"name": "A. Carrasquilla", "sofifa_id": None, "position": "MF"},
        {"name": "A. Andrade", "sofifa_id": None, "position": "MF"},
        {"name": "C. Waterman", "sofifa_id": None, "position": "FW"},
        {"name": "C. Córdoba", "sofifa_id": None, "position": "DF"},
        {"name": "E. Zorrilla", "sofifa_id": None, "position": "MF"},
        {"name": "J. Estuáquio", "sofifa_id": None, "position": "MF"},
        {"name": "R. Sallai", "sofifa_id": None, "position": "FW"},
        {"name": "A. Johnston", "sofifa_id": None, "position": "MF"},
        {"name": "A. Polo", "sofifa_id": None, "position": "FW"},
    ],
    "Costa Rica": [
        {"name": "C. Ajer", "sofifa_id": None, "position": "DF"},
        {"name": "A. Robinson", "sofifa_id": None, "position": "DF"},
        {"name": "T. Adams", "sofifa_id": None, "position": "MF"},
        {"name": "J. Cascante", "sofifa_id": None, "position": "DF"},
        {"name": "K. Vargas", "sofifa_id": None, "position": "MF"},
        {"name": "D. Chacón", "sofifa_id": None, "position": "MF"},
        {"name": "A. Martínez", "sofifa_id": None, "position": "MF"},
        {"name": "B. Ruiz", "sofifa_id": None, "position": "FW"},
        {"name": "L. Díaz", "sofifa_id": None, "position": "MF"},
    ],
    "USA": [
        {"name": "C. Pulisic", "sofifa_id": None, "position": "MF"},
        {"name": "G. Reyna", "sofifa_id": None, "position": "MF"},
        {"name": "W. McKennie", "sofifa_id": None, "position": "MF"},
        {"name": "T. Adams", "sofifa_id": None, "position": "MF"},
        {"name": "A. Robinson", "sofifa_id": None, "position": "DF"},
        {"name": "R. Pulisic", "sofifa_id": None, "position": "MF"},
        {"name": "S. Dest", "sofifa_id": None, "position": "DF"},
        {"name": "F. Balogun", "sofifa_id": None, "position": "FW"},
        {"name": "F. Brown Forbes", "sofifa_id": None, "position": "MF"},
        {"name": "J. Brooks", "sofifa_id": None, "position": "DF"},
        {"name": "M. Turner", "sofifa_id": None, "position": "GK"},
        {"name": "K. Navas", "sofifa_id": None, "position": "GK"},
        {"name": "J. Vargas", "sofifa_id": None, "position": "MF"},
        {"name": "D. Kamada", "sofifa_id": None, "position": "MF"},
        {"name": "K. Nakamura", "sofifa_id": None, "position": "MF"},
        {"name": "Lucas Mendes", "sofifa_id": None, "position": "DF"},
        {"name": "M. Luongo", "sofifa_id": None, "position": "MF"},
        {"name": "M. Solomon", "sofifa_id": None, "position": "MF"},
        {"name": "D. Peretz", "sofifa_id": None, "position": "MF"},
        {"name": "M. Okoye", "sofifa_id": None, "position": "GK"},
    ],
    "Canada": [
        {"name": "A. Davies", "sofifa_id": None, "position": "DF"},
        {"name": "J. David", "sofifa_id": None, "position": "FW"},
        {"name": "T. Buchanan", "sofifa_id": None, "position": "MF"},
        {"name": "A. Johnston", "sofifa_id": None, "position": "MF"},
        {"name": "M. Crépeau", "sofifa_id": None, "position": "GK"},
        {"name": "S. Eustáquio", "sofifa_id": None, "position": "MF"},
        {"name": "L. Bailey", "sofifa_id": None, "position": "FW"},
        {"name": "A. Blake", "sofifa_id": None, "position": "DF"},
        {"name": "D. Gray", "sofifa_id": None, "position": "DF"},
        {"name": "C. Larin", "sofifa_id": None, "position": "FW"},
        {"name": "K. Szymański", "sofifa_id": None, "position": "MF"},
        {"name": "W. Orban", "sofifa_id": None, "position": "DF"},
        {"name": "D. Szoboszlai", "sofifa_id": None, "position": "MF"},
        {"name": "R. Sallai", "sofifa_id": None, "position": "FW"},
        {"name": "Z. Kalmár", "sofifa_id": None, "position": "MF"},
        {"name": "D. Sallói", "sofifa_id": None, "position": "FW"},
        {"name": "K. Lisztes", "sofifa_id": None, "position": "MF"},
        {"name": "A. Bell", "sofifa_id": None, "position": "DF"},
        {"name": "A. Hutchinson", "sofifa_id": None, "position": "DF"},
    ],
    "Jamaica": [
        {"name": "L. Bailey", "sofifa_id": None, "position": "FW"},
        {"name": "K. Roofe", "sofifa_id": None, "position": "FW"},
        {"name": "S. Nicholson", "sofifa_id": None, "position": "FW"},
        {"name": "A. Blake", "sofifa_id": None, "position": "DF"},
        {"name": "B. Steele", "sofifa_id": None, "position": "DF"},
        {"name": "C. Palmer", "sofifa_id": None, "position": "MF"},
        {"name": "A. Johnson", "sofifa_id": None, "position": "MF"},
        {"name": "D. Gray", "sofifa_id": None, "position": "DF"},
    ],

    # ---- AFC ----
    "Korea": [
        {"name": "H. Son", "sofifa_id": None, "position": "FW"},
        {"name": "Hyeon Woo", "sofifa_id": None, "position": "GK"},
        {"name": "Kim Min jae", "sofifa_id": None, "position": "DF"},
        {"name": "Lee Kang In", "sofifa_id": None, "position": "MF"},
        {"name": "Hwang Hee Chan", "sofifa_id": None, "position": "FW"},
        {"name": "Hong Hyeon Seok", "sofifa_id": None, "position": "MF"},
        {"name": "Joo Min Kyu", "sofifa_id": None, "position": "FW"},
        {"name": "Kim Young Gwon", "sofifa_id": None, "position": "DF"},
        {"name": "Lee Jae Sung", "sofifa_id": None, "position": "MF"},
    ],
    "Saudi Arabia": [
        {"name": "A. Al Mayoof", "sofifa_id": None, "position": "GK"},
        {"name": "A. Al Faraj", "sofifa_id": None, "position": "MF"},
        {"name": "A. Al Dawsari", "sofifa_id": None, "position": "FW"},
        {"name": "S. Abdulhamid", "sofifa_id": None, "position": "DF"},
        {"name": "A. Sharahili", "sofifa_id": None, "position": "MF"},
        {"name": "A. Al Bulayhi", "sofifa_id": None, "position": "DF"},
        {"name": "A. Al Shahrani", "sofifa_id": None, "position": "DF"},
        {"name": "A. Al Ayeri", "sofifa_id": None, "position": "FW"},
        {"name": "H. Al Haydos", "sofifa_id": None, "position": "FW"},
        {"name": "H. Ahmed", "sofifa_id": None, "position": "MF"},
        {"name": "D. Peretz", "sofifa_id": None, "position": "MF"},
        {"name": "M. Okoye", "sofifa_id": None, "position": "GK"},
        {"name": "M. Abu Fani", "sofifa_id": None, "position": "MF"},
        {"name": "T. Kubo", "sofifa_id": None, "position": "MF"},
        {"name": "T. Minamino", "sofifa_id": None, "position": "MF"},
        {"name": "R. Doan", "sofifa_id": None, "position": "MF"},
        {"name": "K. Sano", "sofifa_id": None, "position": "MF"},
        {"name": "J. Ito", "sofifa_id": None, "position": "FW"},
        {"name": "R. Safuri", "sofifa_id": None, "position": "MF"},
    ],
    "Japan": [
        {"name": "T. Kubo", "sofifa_id": None, "position": "MF"},
        {"name": "T. Minamino", "sofifa_id": None, "position": "MF"},
        {"name": "R. Doan", "sofifa_id": None, "position": "MF"},
        {"name": "K. Sano", "sofifa_id": None, "position": "MF"},
        {"name": "J. Ito", "sofifa_id": None, "position": "FW"},
        {"name": "D. Kamada", "sofifa_id": None, "position": "MF"},
        {"name": "K. Nakamura", "sofifa_id": None, "position": "MF"},
        {"name": "R. Safuri", "sofifa_id": None, "position": "MF"},
        {"name": "T. Awoniyi", "sofifa_id": None, "position": "FW"},
    ],
    "Australia": [
        {"name": "M. Ryan", "sofifa_id": None, "position": "GK"},
        {"name": "C. Goodwin", "sofifa_id": None, "position": "DF"},
        {"name": "J. Irvine", "sofifa_id": None, "position": "MF"},
        {"name": "M. Leckie", "sofifa_id": None, "position": "FW"},
        {"name": "R. McGree", "sofifa_id": None, "position": "MF"},
        {"name": "A. Grant", "sofifa_id": None, "position": "MF"},
        {"name": "J. Maclaren", "sofifa_id": None, "position": "FW"},
        {"name": "C. Devlin", "sofifa_id": None, "position": "MF"},
        {"name": "A. Adli", "sofifa_id": None, "position": "MF"},
    ],
    "Iran": [
        {"name": "M. Khanzadeh", "sofifa_id": None, "position": "GK"},
        {"name": "S. Azmoun", "sofifa_id": None, "position": "FW"},
        {"name": "M. Taremi", "sofifa_id": None, "position": "FW"},
        {"name": "A. Jahanbakhsh", "sofifa_id": None, "position": "FW"},
        {"name": "M. Ezatolahi", "sofifa_id": None, "position": "MF"},
    ],
    "Qatar": [
        {"name": "H. Al Haydos", "sofifa_id": None, "position": "FW"},
        {"name": "A. Al Ayeri", "sofifa_id": None, "position": "FW"},
        {"name": "M. Abu Fani", "sofifa_id": None, "position": "MF"},
        {"name": "A. Afif", "sofifa_id": None, "position": "FW"},
        {"name": "A. Ali", "sofifa_id": None, "position": "MF"},
        {"name": "T. Baribo", "sofifa_id": None, "position": "FW"},
    ],

    # ---- Repechaje ----
    "New Zealand": [
        {"name": "K. Barbarouses", "sofifa_id": None, "position": "FW"},
        {"name": "B. Old", "sofifa_id": None, "position": "MF"},
        {"name": "T. Partey", "sofifa_id": None, "position": "MF"},
        {"name": "L. Zigi", "sofifa_id": None, "position": "GK"},
        {"name": "A. Paulsen", "sofifa_id": None, "position": "DF"},
        {"name": "A. Rufer", "sofifa_id": None, "position": "DF"},
        {"name": "T. Bindon", "sofifa_id": None, "position": "MF"},
        {"name": "M. Boxall", "sofifa_id": None, "position": "DF"},
        {"name": "C. Wood", "sofifa_id": None, "position": "FW"},
        {"name": "J. Bell", "sofifa_id": None, "position": "MF"},
        {"name": "L. Cacace", "sofifa_id": None, "position": "DF"},
        {"name": "A. Stamenic", "sofifa_id": None, "position": "MF"},
    ],
}

# ============================================================
# RANKING FIFA INICIAL (Puntuación base por confederación/nivel)
# ============================================================
INITIAL_FIFA_RANKING = {
    # UEFA
    "France": 1840, "Spain": 1810, "England": 1780, "Germany": 1750,
    "Portugal": 1720, "Italy": 1690, "Netherlands": 1650, "Belgium": 1620,
    "Croatia": 1580, "Denmark": 1560, "Switzerland": 1530, "Norway": 1480,
    "Austria": 1450, "Sweden": 1420, "Poland": 1390, "Serbia": 1360,
    "Turkey": 1330, "Ukraine": 1310, "Czech Republic": 1280, "Greece": 1250,
    "Scotland": 1220, "Wales": 1200, "Iceland": 1150, "Russia": 1100,
    # CONMEBOL
    "Argentina": 1870, "Brazil": 1830, "Colombia": 1650, "Uruguay": 1620,
    "Chile": 1540, "Ecuador": 1510, "Paraguay": 1430, "Peru": 1380,
    "Bolivia": 1250, "Venezuela": 1230,
    # CAF
    "Senegal": 1630, "Morocco": 1600, "Tunisia": 1530, "Ghana": 1480,
    "Egypt": 1450, "Ivory Coast": 1440, "Nigeria": 1420, "Cameroon": 1390,
    "South Africa": 1330, "Algeria": 1350,
    # CONCACAF
    "Mexico": 1550, "USA": 1530, "Canada": 1490, "Costa Rica": 1380,
    "Panama": 1360, "Jamaica": 1280,
    # AFC
    "Japan": 1560, "Korea": 1530, "Australia": 1470, "Saudi Arabia": 1420,
    "Iran": 1440, "Qatar": 1370,
    # Repechaje
    "New Zealand": 1100,
}

# ============================================================
# CUPOS AL MUNDIAL POR CONFEDERACIÓN
# ============================================================
WORLD_CUP_SLOTS = {
    "UEFA": {
        "direct_euro": 5,          # Top 5 de la Eurocopa
        "playoff_groups": 4,       # 4 grupos de eliminatorias → 2 clasifican c/u = 8
        "playoff_per_group": 2,
        "total": 13
    },
    "CONMEBOL": {
        "direct": 1,               # Campeón Copa América
        "playoff_direct": 3,       # Puestos 2-7 → todos vs todos → top 3
        "repechaje": 1,            # 4to puesto
        "total": 4
    },
    "CAF": {
        "direct": 2,               # Campeón y subcampeón Copa África
        "playoff_direct": 3,       # Puestos 3-7 → todos vs todos → top 3
        "total": 5
    },
    "CONCACAF": {
        "direct": 1,               # Campeón Copa Oro
        "playoff_direct": 2,       # Puestos 2-5 → todos vs todos → top 2
        "repechaje": 1,            # 3er puesto
        "total": 3
    },
    "AFC": {
        "direct": 1,               # Campeón Copa Asia
        "playoff_direct": 3,       # Puestos 2-5 → todos vs todos → top 3
        "repechaje": 1,            # 4to puesto
        "total": 4
    },
}

# Repechaje internacional
PLAYOFF_MATCHES = [
    ("CONCACAF_3rd", "AFC_4th"),
    ("CONMEBOL_4th", "New Zealand"),
]

# Puntos FIFA por resultado
FIFA_POINTS = {
    "win": 3,
    "draw": 1,
    "loss": 0,
    "group_stage_win": 3,
    "group_stage_draw": 1,
    "round_of_16_win": 4,
    "quarter_win": 5,
    "semi_win": 7,
    "final_win": 10,
    "champion": 15,
}
